woowacourse-teams/2024-staccato

backend/src/main/java/com/staccato/config/JpaAuditingConfig.java, backend/src/main/java/com/staccato/config/domain/BaseEntity.java, backend/src/main/java/com/staccato/member/domain/Member.java, backend/src/main/java/com/staccato/pin/domain/Pin.java, backend/src/main/java/com/staccato/travel/domain/Mate.java, backend/src/main/java/com/staccato/travel/domain/Travel.java, backend/src/main/java/com/staccato/visit/domain/Visit.java, backend/src/main/java/com/staccato/visit/domain/VisitImage.java, backend/src/main/java/com/staccato/visit/domain/VisitLog.java, backend/src/main/resources/application.yml
- #2 
- 작성한 ERD를 기반으로 JPA Entity 구성
- 작성된 `ERD`에서는 `created_at`이 `LocalDate`로 표현이 되었지만, `log`를 남기기 위한 목적임을 감안해 `LocalDateTime`으로 변경하는 것을 고려 중
- `h2` 는 `TinyInt`를 지원하지 않아 따로 `columnDefinition`으로 명시하지 않았습니다.
- API 기능 중심으로 역할 분담
=> feat: Entity 구성 #2

.github/workflows/android-ci.yml
- #38 
- **Git Actions Secret**에 local.properties 접근에 대한 **API key를 설정**한다.
**`android-ci.yml` 에 추가된 코드**   
```
- name: Access LOCAL_PROPERTIES_API_KEY
run: |
echo LOCAL_PROPERTIES_API_KEY=\"$LOCAL_PROPERTIES_API_KEY\" >> local.properties
shell: bash
env:
$LOCAL_PROPERTIES_API_KEY: ${{ secrets.LOCAL_PROPERTIES_API_KEY }}
```
**코드 설명**
- Git Action에 Secret으로 저장된 LOCAL_PROPERTIES_API_KEY를 `secret`에 접근하여 환경 변수로 가져온다.
- 가져온 변수를 echo를 활용하여 local.properties에 설정할 수 있다.
- 이로써 CI 과정에서 원격에서도 local.properties를 직접 설정하여 해당 파일에 접근할 수 있다.
- 이후 PR 요청에서 CI workflow가 문제 없이 통과되는지 확인해주세요!
- 해당 커밋을 local의 `develop-an` 브랜치에 전파 후 Merge 필요
- 각 local의 `local.properties` 에 해당 Api key 값을 설정하여야 함
```
// in local.properties
// add this various
LOCAL_PROPERTIES_API_KEY="our_local_properties_key_value"
```
=> build: develop-an의 CI 설정 수정 #38

.github/workflows/backend-ci-cd-dev.yml, backend/docker-compose.yml, backend/src/main/resources/application.yml
- #28 
- Docker, Docker-Compose를 활용한 CI/CD 구성
=> build: CD yml 파일 구성 #28

backend/src/main/java/com/staccato/visit/domain/VisitImage.java, backend/src/main/java/com/staccato/visit/repository/VisitImageRepository.java, backend/src/main/java/com/staccato/visit/repository/VisitLogRepository.java, backend/src/main/java/com/staccato/visit/service/VisitService.java, backend/src/test/java/com/staccato/visit/repository/VisitImageRepositoryTest.java, backend/src/test/java/com/staccato/visit/repository/VisitLogRepositoryTest.java, backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
- #65 
- 특정 방문 기록 삭제 API 호출 시 관련된 VisitImage를 모두 삭제하도록 수정
=> fix: 특정 방문 기록 삭제 API 호출 시 관련된 VisitImage를 모두 삭제하도록 수정 #65

android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/BindingAdapters.kt
- #58 
둥근 모서리 이미지를 출력하는 바인딩 어댑터를 추가했습니다!
아래 설명을 참고해주세요.
- **Coil**
- **세 가지 속성** 모두 필요
- `app:coilRoundedCornerImageUrl` : 둥근 모서리로 나타내고자 하는 이미지 URL
- `app:coilPlaceHolder` : placeHolder URL
- `app:coilRoundingRadius` : **`Float`** 형, 모서리의 둥근 정도
- xml의 `scaleType` 속성에 `"centerCrop"` 값을 줄 필요 없음.
- **Glide**
- 마찬가지로, **세 가지 속성** 모두 필요
- `app:glideRoundedCornerImageUrl` : 둥근 모서리로 나타내고자 하는 이미지 URL
- `app:glidePlaceHolder` : placeHolder URL
- `app:glideRoundingRadius` : **`Int`** 형, 모서리의 둥근 정도
- 마찬가지로 xml의 `scaleType` 속성에 `"centerCrop"` 값을 줄 필요 없음.
- **Coil**
```xml
<ImageView
android:layout_width="200dp"
android:layout_height="150dp"
app:coilRoundedCornerImageUrl="@{ yourImageUrl }"
app:coilPlaceHolder="@{ yourPlaceHolderDrawable }"
app:coilRoundingRadius="@{ 50f (put Float here) }" />
```
- …
=> feat: 둥근 모서리의 이미지를 로드하는 BindingAdapters 추가 #58

backend/src/main/java/com/staccato/member/service/dto/response/MemberResponse.java, backend/src/main/java/com/staccato/travel/controller/TravelController.java, backend/src/main/java/com/staccato/travel/repository/TravelRepository.java, backend/src/main/java/com/staccato/travel/service/TravelService.java, backend/src/main/java/com/staccato/travel/service/dto/response/TravelDetailResponse.java, backend/src/main/java/com/staccato/travel/service/dto/response/TravelResponse.java, backend/src/main/java/com/staccato/visit/repository/VisitImageRepository.java, backend/src/main/java/com/staccato/visit/repository/VisitRepository.java, backend/src/main/java/com/staccato/visit/service/dto/response/VisitResponse.java, backend/src/main/java/com/staccato/visit/service/dto/response/VisitResponses.java, backend/src/test/java/com/staccato/travel/controller/TravelIntegrationTest.java, backend/src/test/java/com/staccato/travel/domain/TravelTest.java, backend/src/test/java/com/staccato/travel/service/TravelServiceTest.java, backend/src/test/java/com/staccato/visit/repository/VisitLogRepositoryTest.java, backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
- close #20 
- 응답이 null인 필드는 포함시키지 않도록 구현
- 특정 상세 조회용 응답 구현 (TravelDetailResponse, VisitResponse, VisitResponses)
=> feat: 특정 여행 상세 조회 API 구현 #20

backend/src/main/java/com/staccato/travel/controller/TravelController.java, backend/src/main/java/com/staccato/travel/service/TravelService.java, backend/src/main/java/com/staccato/visit/repository/VisitRepository.java, backend/src/test/java/com/staccato/travel/controller/TravelIntegrationTest.java, backend/src/test/java/com/staccato/travel/domain/TravelTest.java, backend/src/test/java/com/staccato/travel/service/TravelServiceTest.java
- #24 
- 특정 여행 상세 삭제 API 구현
- 방문기록이 있는 경우 삭제가 불가능하게 구현하였는데, 회의에서 말했던 것 처럼 여행 상세가 삭제 될 때 우선 논리적 삭제가 특정 여행 상세에 포함된 방문 기록들에게도 전파되게 구성했습니다.
=> feat: 특정 여행 상세 삭제 API 구현 #24

backend/src/main/java/com/staccato/travel/service/TravelService.java, backend/src/main/java/com/staccato/visit/domain/Visit.java, backend/src/main/java/com/staccato/visit/domain/VisitImage.java, backend/src/main/java/com/staccato/visit/domain/VisitLog.java, backend/src/main/java/com/staccato/visit/repository/VisitImageRepository.java, backend/src/main/java/com/staccato/visit/repository/VisitLogRepository.java, backend/src/main/java/com/staccato/visit/repository/VisitRepository.java, backend/src/main/java/com/staccato/visit/service/VisitService.java, backend/src/test/java/com/staccato/visit/repository/VisitImageRepositoryTest.java, backend/src/test/java/com/staccato/visit/repository/VisitLogRepositoryTest.java, backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
- #87 
- 구체적인 구현 내용은 Issue를 참고해주세요
- 양방향 관계 설정으로 cascade를 사용하여 여행 & 방문기록 삭제 로직이 변경되었습니다.
- 양방향 관계 설정 및 cascade에 대한 학습이 부족한 상태입니다. 놓친 부분이나 오류가 없는지 테스트로 확인했으나 꼼꼼한 리뷰 부탁드립니다!
=> feat: VisitLog, VisitImage 양방향 관계 설정 및 논리적 삭제 제거 #87

backend/src/main/java/com/staccato/travel/domain/Travel.java, backend/src/main/java/com/staccato/travel/service/dto/request/TravelRequest.java, backend/src/test/java/com/staccato/travel/domain/TravelTest.java
- #90 
- 여행 생성 시 썸네일을 저장하지 않는 오류 수정
- 여행 상세 수정 날짜 필터링 오류 수정
=> fix: 여행 상세 수정 날짜 필터링 오류와 썸네일 저장 오류 수정 #90

backend/src/main/java/com/staccato/travel/domain/Travel.java, backend/src/main/java/com/staccato/travel/service/TravelService.java, backend/src/main/java/com/staccato/visit/repository/VisitRepository.java, backend/src/test/java/com/staccato/travel/service/TravelServiceTest.java
- #103 
- Travel 삭제시 연관된 TravelMember에도 논리적 삭제가 전파되도록 수정
-  방문 기록이 남아있을 때 Travel을 삭제 불가능하게 만드는 validation에서, 방문 기록의 isDeleted flag를 확인하도록 수정
=> fix: Travel 삭제시 발생하는 오류 수정 #103

backend/src/main/java/com/staccato/config/domain/BaseEntity.java, backend/src/main/java/com/staccato/member/domain/Member.java, backend/src/main/java/com/staccato/travel/domain/Travel.java, backend/src/main/java/com/staccato/travel/domain/TravelMember.java, backend/src/main/java/com/staccato/visit/domain/Visit.java, backend/src/main/java/com/staccato/visit/domain/VisitLog.java, backend/src/main/resources/application.yml
- #132 
- member에 남아있는 `@SqlRestriction`은 제거하는 방향으로 리팩터링 필요
=> refactor: member entity 외 논리적 삭제 제거 #132

android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/BindingAdapters.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/common/PhotoAttachFragment.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/common/PhotoAttachHandler.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/util/FileUtils.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/visitcreation/OnUrisSelectedListener.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/visitcreation/VisitCreationActivity.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/visitcreation/viewmodel/VisitCreationViewModel.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/visitupdate/VisitUpdateActivity.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/visitupdate/viewmodel/VisitUpdateViewModel.kt, android/Staccato_AN/app/src/main/res/layout/activity_visit_creation.xml, android/Staccato_AN/app/src/main/res/layout/activity_visit_update.xml, android/Staccato_AN/app/src/main/res/layout/fragment_photo_attach.xml, android/Staccato_AN/app/src/main/res/values/strings.xml, android/Staccato_AN/app/src/main/res/values/styles.xml
- #150 
- 카메라 열기 플로우 구현
- 선택된 사진 가로 리사이클러뷰로 보여주기
- 선택된 사진을 선택 취소할 수 있도록 하기
=> feat: 방문 생성 화면, 방문 수정 화면에서 갤러리 사진 불러오기 구현 #150

backend/src/main/java/com/staccato/visit/controller/VisitController.java, backend/src/main/java/com/staccato/visit/controller/docs/VisitControllerDocs.java, backend/src/main/java/com/staccato/visit/service/VisitService.java, backend/src/main/resources/application.yml, backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java, backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
- #140 
- 방문 기록 조회, 수정 삭제에 인가 구현
- 방문 기록 생성 시에도 여행의 소유자인지 확인하는 인가 절차 추가
=> feat: 방문 기록 관련 인가 구현 #140

android/Staccato_AN/app/build.gradle.kts, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/ApiResponseHandler.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/HeaderInterceptor.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/ResponseResult.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/StaccatoClient.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/dto/ErrorResponse.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/dto/Status.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/travel/TravelApiService.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/travel/TravelDataSource.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/travel/TravelDefaultRepository.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/travel/TravelRemoteDataSource.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/domain/repository/TravelRepository.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/travel/TravelFragment.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/travel/TravelHandler.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/travel/viewmodel/TravelViewModel.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/travelcreation/viewmodel/TravelCreationViewModel.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/travelupdate/viewmodel/TravelUpdateViewModel.kt
- #153 
<br>
https://github.com/user-attachments/assets/3970aad9-73fc-4e70-ba48-51683192aa57
- api service 구현
- data source 구현
- repository 구현
- api 연결
<br>
- 방문 기록이 없을 때만 여행 상세가 삭제됩니다.
- To. @Junyoung-WON 
- 여행 상세 삭제 후 타임라인에 변경된 데이터가 실시간으로 반영되지 않고 있습니다. 해당 부분 수정 부탁드려요!
<br>
- api 명세 변경에 따른 로직 수정
=> feat: 특정 여행 상세 삭제 api 연결 #153

.github/workflows/backend-ci-cd-dev.yml, backend/src/main/java/com/staccato/s3/service/CloudStorageService.java, backend/src/main/java/com/staccato/travel/service/TravelService.java, backend/src/main/java/com/staccato/visit/controller/VisitController.java, backend/src/main/java/com/staccato/visit/service/VisitService.java, backend/src/main/java/com/staccato/visit/service/dto/request/VisitRequest.java, backend/src/test/java/com/staccato/FakeCloudStorageClient.java, backend/src/test/java/com/staccato/ServiceSliceTest.java, backend/src/test/java/com/staccato/TestConfig.java, backend/src/test/java/com/staccato/travel/service/TravelServiceTest.java, backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java, backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
- #166 
S3 적용이 필요한 API들 변경
- 여행 상세 생성 API
- 여행 상세 수정 API
- 방문 기록 생성 API
- 방문 기록 수정 API
썸네일 삭제 또는 방문 기록 사진 삭제 시 DB에는 URL이 삭제되지만 S3 파일 자체는 삭제되지 않습니다. S3에서 제공하는 delete 메서드가 우리의 service 메서드의 트랜잭션 안에 포함될 수 없어서 적용하지 못했는데, 이 문제를 고민해보고 적용해보면 좋겠어요.
=> feat: 이미지가 필요한 API에 S3 적용 #166

.github/workflows/backend-ci-cd-dev.yml, backend/src/main/java/com/staccato/config/log/LogForm.java, backend/src/main/java/com/staccato/config/log/LoggingFilter.java, backend/src/main/java/com/staccato/exception/GlobalExceptionHandler.java, backend/src/main/resources/console-appender.xml, backend/src/main/resources/error-appender.xml, backend/src/main/resources/info-appender.xml, backend/src/main/resources/logback-spring.xml, backend/src/main/resources/warn-appender.xml
- #134 
- `INFO`
- filter에서 요청, 응답 → `INFO`
- application level error : 500 외 → `WARN`
- application level error : 500 → `ERROR`
- `filter`에서 `memberId` 추출 방식 고민
=> feat: 로깅 프레임워크 적용 #134

backend/src/main/java/com/staccato/exception/GlobalExceptionHandler.java, backend/src/main/java/com/staccato/member/service/dto/response/MemberResponse.java, backend/src/main/java/com/staccato/travel/domain/Travel.java, backend/src/main/java/com/staccato/travel/service/dto/request/TravelRequest.java, backend/src/main/java/com/staccato/travel/service/dto/response/TravelDetailResponse.java, backend/src/main/java/com/staccato/travel/service/dto/response/TravelResponse.java, backend/src/main/java/com/staccato/travel/service/dto/response/VisitResponse.java, backend/src/main/java/com/staccato/visit/domain/Visit.java, backend/src/main/java/com/staccato/visit/service/dto/request/VisitRequest.java, backend/src/main/java/com/staccato/visit/service/dto/response/VisitDetailResponse.java, backend/src/main/java/com/staccato/visit/service/dto/response/VisitLogResponse.java, backend/src/test/java/com/staccato/travel/controller/TravelControllerTest.java, backend/src/test/java/com/staccato/travel/domain/TravelTest.java, backend/src/test/java/com/staccato/travel/service/TravelServiceTest.java, backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java, backend/src/test/java/com/staccato/visit/domain/VisitImagesTest.java, backend/src/test/java/com/staccato/visit/domain/VisitTest.java, backend/src/test/java/com/staccato/visit/fixture/VisitFixture.java, backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
- #173 
- Visit의 visitedAt이 LocalDate -> LocalDateTime으로 변경
- 이에 따라 변경이 필요한 테스트 코드들 수정
- 시간까지 고려하여 정렬이 잘 되는지 테스트 코드 수정
- visitedAt이 포함된 각종 response dto의 경우, 시간까지는 필요하지 않으므로 기존과 같이 LocalDate 사용
`visitedAt`이 `yyyy-MM-dd'T'HH:mm:ss` 형식으로 오지 않았을 때, 아래의 `ExceptionHandler` 메서드가 동작할 것으로 기대했습니다.
```java
@ExceptionHandler(DateTimeParseException.class)
@ApiResponse(responseCode = "400")
public ResponseEntity<ExceptionResponse> handleDateTimeParseException(DateTimeParseException e) {
String errorMessage = "올바르지 않은 날짜 형식입니다.";
ExceptionResponse exceptionResponse = new ExceptionResponse(HttpStatus.BAD_REQUEST.toString(), errorMessage);
log.warn(LogForm.EXCEPTION_LOGGING_FORM, exceptionResponse);
return ResponseEntity.badRequest().body(exceptionResponse);
}
```
그런데 위 메서드가 작동하지 않고 아래 메서드가 작동합니다.
```java …
```
=> feat: 방문 기록 목록 조회시 시간 순으로도 정렬되는 기능 구현

backend/src/main/java/com/staccato/s3/service/CloudStorageService.java
- #176 
< 파일 이름을 `UUID`로만 구성하도록 수정 >
- 파일 이름에 한글이 들어가는 경우 깨지는 현상이 발생하여, UUID로만 파일 이름을 구성하도록 변경했습니다.
- 파일 이름이 깨지면, S3에서 url 클릭 시, 이미지를 띄우는 대신 이미지를 다운로드 해버리는 현상도 추가로 발견해서 고치고자 이를 수행했습니다.
< `Content-type`을 `multipart/formed-data`로 고정 >
- S3에서 파일 유형이 빈 채로 전달되는 것을 확인
- `Content-type`이 `multipart/formed-data`인 경우 파일 유형을 잘 인식했습니다.
- 따라서 값을 하나로 고정시켜 파일 형식을 자동으로 읽도록 변경했습니다.
=> refactor: 파일 이름 및 형식 오류 수정 #176

android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/dto/mapper/TravelMapper.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/dto/travel/TravelUpdateRequest.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/travel/TravelApiService.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/travel/TravelDataSource.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/travel/TravelDefaultRepository.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/travel/TravelRemoteDataSource.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/domain/repository/TravelRepository.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/BindingAdapters.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/travel/viewmodel/TravelViewModel.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/travelcreation/viewmodel/TravelCreationViewModel.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/travelupdate/TravelUpdateActivity.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/travelupdate/TravelUpdateHandler.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/travelupdate/viewmodel/TravelUpdateViewModel.kt, android/Staccato_AN/app/src/main/res/layout/activity_travel_creation.xml, android/Staccato_AN/app/src/main/res/layout/activity_travel_update.xml, android/Staccato_AN/app/src/main/res/layout/item_visits.xml, android/Staccato_AN/app/src/main/res/values/strings.xml
- #180 
<br>
- 이미지 파일 로드
- MultiPart
- 여행 상세 수정 로직 변경
- 로딩 view 추가
- 여행 기능 리팩터링
<br>
<br>
여행 상세 수정 기능 api 변경 중 아래 버그들을 발견해 수정했습니다.
- 삭제 불가능한 여행 삭제 시도 관련 에러 토스트 문제 해결
- 여행 소개 미입력 시 여행이 생성 되지 않는 오류 해결
<br>
=> feat: 여행 상세 수정 기능 api 변경 및 여행 리팩터링 #180

backend/src/main/java/com/staccato/auth/service/dto/request/LoginRequest.java, backend/src/main/java/com/staccato/member/domain/Nickname.java, backend/src/main/java/com/staccato/travel/service/dto/request/TravelRequest.java, backend/src/main/java/com/staccato/visit/service/dto/request/VisitRequest.java, backend/src/test/java/com/staccato/auth/controller/AuthControllerTest.java, backend/src/test/java/com/staccato/member/domain/NicknameTest.java, backend/src/test/java/com/staccato/travel/controller/TravelControllerTest.java, backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
- #186 
- NotNull -> NotBlank : 공백, 빈, null 문자열이 오지 못하도록 예외 처리
- Size(max= -) -> Size(min=-, max=-) : 최소도 체크하고, 메세지에도 반영
=> feat: 빈/공백 문자열 예외 처리 #186

backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-local.yml, backend/src/main/resources/application-stage.yml
- #205 
- 이미지 용량 제한을 확장했습니다.
- 한 장 용량 제한: 20MB
- 한 번 요청 제한: 100MB
dev 서버와 stage 서버의 `nginx.conf` 파일의 http block에 내용 추가
```ssh
http {
##
##
client_max_body_size 100M;
...
}
```
=> refactor: 이미지 용량 제한 확장 #205

backend/src/main/java/com/staccato/auth/service/AuthService.java, backend/src/main/java/com/staccato/config/log/LogForm.java, backend/src/main/java/com/staccato/config/log/LoggingFilter.java, backend/src/main/java/com/staccato/exception/GlobalExceptionHandler.java, backend/src/main/resources/console-appender.xml, backend/src/main/resources/error-appender.xml, backend/src/main/resources/info-appender.xml, backend/src/main/resources/warn-appender.xml
- #190 
- MDC를 적용해서 request_id를 통해 사용자 요청을 추적가능하게 구성
- (아래 사진은 `local` 환경이므로 `Info` 에 클래스, 메서드 등이 포함되는데 `stage`, `dev`에는 보이지 않게끔 설정해 놓았습니다.)
- 사용자 인증 정보 로깅
- `[2024-08-15 21:59:22:36083] [http-nio-8080-exec-3] [request_id=43abd78c-9257-4909-a54a-90147cdc33ce] INFO  [com.staccato.auth.service.AuthService.extractFromToken.-56] - [Login Member ID : 1 | Login Member Nickname : hotea]`
- 스프링 기본 로그들 중 크리티컬 하지 않은 로그들은 모두 로깅에서 제외
- `Service CRUD` 메서드마다 로깅을 추가하게 된다면 무의미하고 방대한 로깅만 남겠다고 생각되어서 설정해놓지 않았습니다.
- 추후에 필요한 경우 구성예정
=> feat: 사용자 로깅, Nginx 로깅, DB 로깅 #190

backend/src/main/java/com/staccato/comment/controller/CommentController.java, backend/src/main/java/com/staccato/comment/controller/docs/CommentControllerDocs.java, backend/src/main/java/com/staccato/comment/domain/Comment.java, backend/src/main/java/com/staccato/comment/service/CommentService.java, backend/src/main/java/com/staccato/comment/service/dto/request/CommentRequest.java, backend/src/main/java/com/staccato/comment/service/dto/request/CommentUpdateRequest.java, backend/src/main/java/com/staccato/exception/validation/ValidationSteps.java, backend/src/main/java/com/staccato/member/domain/Member.java, backend/src/main/java/com/staccato/memory/domain/MemoryMember.java, backend/src/test/java/com/staccato/comment/controller/CommentControllerTest.java, backend/src/test/java/com/staccato/comment/service/CommentServiceTest.java, backend/src/test/java/com/staccato/fixture/memory/MemoryFixture.java, backend/src/test/java/com/staccato/fixture/moment/MomentFixture.java
- #245
- 댓글 수정 API 구현
- Controller, DTO 단에 Swagger 적용
댓글 생성 때 사용하는 CommentRequest를 댓글 수정을 요청하는 DTO로 재활용할 수도 있었는데요. 제 생각에는 API별로 DTO를 분리하는 것이 단일 책임 원칙에도 부합하고, API명세에 변경사항이 생겼을 때 유지보수 지점이 명확하여 관리하기가 더 쉬울 것이라 생각해서 분리했습니다. 이에 대해 어떻게 생각하시는지 궁금해요!
=> feat: 댓글 수정 API 구현 #245

.github/workflows/backend-ci-cd-dev.yml, backend/src/main/java/com/staccato/exception/GlobalExceptionHandler.java
- #268 
- image upload 시, `MissingServletRequestPartException` 에러 핸들링 추가
- Request Body가 multipart 형식이 아닌, 적절하지 않은 형태인 경우 해당 에러 발생
=> feat: image upload 예외 처리 추가 #268

backend/src/main/java/com/staccato/image/service/ImageService.java, backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-local.yml, backend/src/main/resources/application-stage.yml
- #271 
- 서버 별로 이미지 저장 경로 설정
- `dev`, `stage` -> staccato/image
- `prod` -> staccato/image-prod
=> feat: 서버 별로 이미지 저장 경로 설정

backend/src/main/java/com/staccato/memory/controller/docs/MemoryControllerDocs.java, backend/src/main/java/com/staccato/memory/domain/Memory.java, backend/src/main/java/com/staccato/memory/repository/MemoryRepository.java, backend/src/main/java/com/staccato/memory/service/MemoryService.java, backend/src/test/java/com/staccato/fixture/memory/MemoryRequestFixture.java, backend/src/test/java/com/staccato/memory/domain/MemoryTest.java, backend/src/test/java/com/staccato/memory/service/MemoryServiceTest.java, backend/src/test/java/com/staccato/moment/service/MomentServiceTest.java
- #280
- 추억을 생성할 때 이미 존재하는 이름으로는 생성할 수 없다.
- 추억을 수정할 때 본래 해당 추억의 이름이 아닌 이미 존재하는 타 추억의 이름으로 변경할 수 없다.
- 픽스처 리팩터링
=> feat: 추억 이름 중복 불가 예외 처리 #280

.github/workflows/android-cd.yml, .github/workflows/android-ci-cd-demo-apk.yml
- #315 
- upload-artifact 는 defaults 설정의 working-directory 경로가 적용되지 않음
=> build: Android CD 수정

android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/main/SharedViewModel.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/maps/MapsFragment.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/maps/MapsViewModel.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/memory/MemoryFragment.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/moment/MomentFragment.kt
- #326 
<br>
- 스타카토 생성, 삭제 후 지도 화면의 마커가 갱신되지 않는 오류 해결
- 지도 로드 시 현위치로 카메라 이동
<br>
(추후 작성)
<br>
<br>
=> fix: 스타카토 생성, 삭제 후 지도 화면의 마커가 갱신되지 않는 오류 해결 #326

android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/BindingAdapters.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/memorycreation/MemoryCreationActivity.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/memoryupdate/MemoryUpdateActivity.kt, android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/memoryupdate/viewmodel/MemoryUpdateViewModel.kt, android/Staccato_AN/app/src/main/res/layout/activity_memory_creation.xml, android/Staccato_AN/app/src/main/res/layout/activity_memory_update.xml
- #332 
<br>
- 추억 생성 이미지 로딩 중 표시 및 저장 버튼 비활성화
- 추억 수정 이미지 로딩 중 표시 및 저장 버튼 비활성화
=> feat: 추억 생성 및 수정 이미지 로딩 중 표시 및 저장 버튼 비활성화 #332

backend/src/main/java/com/staccato/memory/domain/Term.java, backend/src/test/java/com/staccato/memory/controller/MemoryControllerTest.java, backend/src/test/java/com/staccato/memory/domain/TermTest.java, backend/src/test/java/com/staccato/memory/service/MemoryServiceTest.java
- #350 
- 아래 세 가지 기능이 가능하도록 수정하려 했으나, 리니가 미리 이에 대비하여 로직을 짜두었네요(리니 짱👍). 따라서 프로덕션 코드에는 변경사항이 없습니다. 
- memory request DTO에 기간과 관련된 필드를 nullable하게 만듭니다. 
- Term 객체 생성 시 startAt과 endAt이 null이더라도 생성이 가능하도록 만듭니다. 단, 둘 중 하나만 null인 경우는 허용하지 않습니다.
- memory가 가진 Term의 startAt, endAt이 null이라면 어떤 날짜의 스타카토든 포함할 수 있도록 만듭니다.
- 따라서 테스트 코드를 몇 개 추가한 것이 끝입니다.
추억 생성 시 시작 날짜와 끝 날짜 중 하나만 입력해서 요청이 오면, 현재 서버 단에서는 `추억 시작 날짜와 끝 날짜를 모두 입력해주세요.`라는 예외 메시지를 던집니다. 그런데 이제 시작 날짜와 끝 날짜를 모두 입력하지 않은 경우도 가능하게 되었습니다. 따라서 `시작 날짜와 끝 날짜 모두 입력하거나 모두 입력하지 않아야 합니다.`라는 의미의 예외를 던지는 것이 좋을 것 같아요. 근데 좋은 예외메시지가 잘 떠오르질 않네요. 혹시나 좋은 메시지가 떠오르면 추천해주세요! (잘 안 떠오르면 일단 넘어가도 될 것 같습니다)
- 현재는 사용자가 시작 날짜와 끝 날짜를 모두 선택하지 않고선 추억 생성 버튼이 비활성화 되는 것으로 알고 있습니다. 시작 날짜와 끝 날짜 중 하나만 선택했을 때에는 추억 생성 버튼이 여전히 비활성화되고, 둘 다 선택하거나 둘 다 선택하지 않았을 때에만 활성화 되도록 변경되어야겠네요.
- DB …
=> feat: 추억 생성/수정 시 기간을 nullable하게 변경 #350

.github/workflows/backend-ci-cd-dev.yml, backend/src/main/java/com/staccato/memory/controller/docs/MemoryControllerDocs.java, backend/src/main/java/com/staccato/memory/domain/Term.java, backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-local.yml, backend/src/main/resources/application-prod.yml, backend/src/main/resources/application-stage.yml, backend/src/test/java/com/staccato/memory/service/MemoryServiceTest.java
- #371
- 하이버네이트는 Entity 로딩 과정에서 Embedded Type의 모든 Field값이 null이면 인스턴스화하지 않는다.
- 이로 인해, 추억 기간 미설정 시, 조회하면 NPE가 발생 (ex: `memory.getTerm().getStart()`) 
- create_empty_composites.enabled = true로 `@Embedded` 객체의 모든 필드가 null이어도 해당 객체 자체가 null이 되는 것을 방지
참고: https://hibernate.atlassian.net/browse/HHH-7610
- 컨트롤러 테스트 작성
=> fix: embedded 인스턴스화  관련 NPE 버그 해결

backend/src/main/java/com/staccato/auth/controller/AuthController.java, backend/src/main/java/com/staccato/auth/service/AuthService.java, backend/src/main/java/com/staccato/comment/controller/CommentController.java, backend/src/main/java/com/staccato/comment/service/CommentService.java, backend/src/main/java/com/staccato/config/log/LogForm.java, backend/src/main/java/com/staccato/config/log/TraceAspect.java, backend/src/main/java/com/staccato/config/log/annotation/Trace.java, backend/src/main/java/com/staccato/exception/GlobalExceptionHandler.java, backend/src/main/java/com/staccato/image/controller/ImageController.java, backend/src/main/java/com/staccato/image/service/ImageService.java, backend/src/main/java/com/staccato/memory/controller/MemoryController.java, backend/src/main/java/com/staccato/memory/service/MemoryService.java, backend/src/main/java/com/staccato/moment/controller/MomentController.java, backend/src/main/java/com/staccato/moment/service/MomentService.java
- #351 
- 예상가능한, 의도한 에러(`StaccatoException`) → `INFO`
- 예상하지 못한 에러면서 **비정상적인 사용자 행동**이나 **잘못된 입력**으로 인해 발생한 예외의 경우(`HttpMessageNotReadableException`, `ForbiddenException`, `etc`) → `WARN`
- `RunTimeException` → `ERROR`
- `DB SQL` 관련 `Exception` 중 특정 에러는 `ERROR`, 다른 특정 에러는 `WARN`이 될 것 같다.
- 우선 크리티컬한(`ERROR`) 것들만 `GlobalExeptionHandelr`에 등록
- `CannotCreateTransactionException`
- **DB 커넥션 실패**
- `DataAccessException`
- **SQL 구문 오류**
- `TransactionSystemException`
- **트랜잭션 실패**
- Index를 걸때 생성하는 부분에서는 더 손해이지만, 조회하는 부분에서 큰 이점이 있어 적용하는데, 만약 A 컬럼을 이용하는데 조회보다 생성하는 부분이 많다면? A컬럼에는 index를 걸지 않는 쪽이 이득이다. 이것을 확인할려면 각 메서드마다 logging을 남겨야 확인 가능할 수 있다.
- `AOP`를 적용하면서 아래와 같은 `log`를 남기게끔 구성하였는데,
``` 
[2024-09-09 19:52:46:52696] [http-nio-8080-exec-3] [request_id=4b5eed9f-3be8-417a-87e4-b0ff36201442] INFO …
```
=> feat: Logging 레벨 수정 및 DB 예외 로깅, AOP 적용 #351

.github/workflows/backend-ci-cd-prod.yml, backend/src/main/java/com/staccato/config/db/DataSourceConfig.java, backend/src/main/java/com/staccato/config/db/DynamicRoutingDataSource.java, backend/src/main/java/com/staccato/config/db/ReaderDataSourceConfig.java, backend/src/main/java/com/staccato/config/db/WriterDataSourceConfig.java, backend/src/main/resources/application-prod.yml, backend/src/test/java/com/staccato/moment/controller/MomentControllerTest.java
=> feat: DB 마이그레이션 #386

backend/src/main/java/com/staccato/moment/service/dto/response/MomentDetailResponse.java, backend/src/test/java/com/staccato/fixture/moment/MomentDetailResponseFixture.java, backend/src/test/java/com/staccato/fixture/moment/MomentFixture.java
- #390 
- 구글맵API를 붙였기 때문에, 스타카토 수정시 위치를 변경할 수 있게 되었습니다.
- 스타카토 수정 페이지에 들어갈 때, 기존 데이터를 미리 채워야하기 때문에 스타카토 조회가 일어납니다. (MomentDetailResponse)
- 현재 스타카토 조회시(MomentDetailResponse) 위도 경도를 보내주고 있지 않습니다.
- 스타카토 수정 요청을 보내려면 위도 경도값도 다시 보내줘야 하는데, 조회시 위도경도가 없으므로 위치를 바꾸지 않았을 때 문제가 생깁니다.
- 따라서 MomentDetailResponse에 위도경도 필드를 추가했습니다.
- 매우 간단한 수정입니다~
=> fix: 특정 스타카토 조회시 위도,경도도 함께 반환 #390

backend/src/main/java/com/staccato/comment/domain/Comment.java, backend/src/main/java/com/staccato/comment/repository/CommentRepository.java, backend/src/main/java/com/staccato/comment/service/CommentService.java, backend/src/main/java/com/staccato/memory/repository/MemoryMemberRepository.java, backend/src/main/java/com/staccato/memory/service/MemoryService.java, backend/src/test/java/com/staccato/memory/repository/MemoryMemberRepositoryTest.java, backend/src/test/java/com/staccato/memory/service/MemoryServiceTest.java
- #404 
- 추억 조회 시 created_at 기준 정렬을 하는데, 이를 DB단이 아닌 애플리케이션 단에서 수행하도록 변경했습니다.
- 특정 스타카토에 댓글의 갯수는 일반적으로 매우 적을 것이라 예상됩니다. 댓글의 전체 갯수는 다른 테이블에 비해 가장 많은 편이라 DB의 용량을 꽤나 큰 비율로 차지할텐데, 아주 작은 양의 정렬을 위해 (moment_id, created_at)에 대한 복합인덱스를 거는 것은 DB용량 측면에서 손해라고 생각합니다. 따라서 복합인덱스를 거는 대신 애플리케이션 단에서 정렬했습니다. 
-  예상과 다르게 특정 스타카토에 평균적으로 많은 양의 댓글이 달린다면 복합인덱스를 고려해도 좋겠습니다.
=> refactor: 추억 조회 시 created_at 기준 정렬을 DB단이 아닌 애플리케이션 단에서 수행 #404

backend/src/main/java/com/staccato/moment/service/dto/response/MomentDetailResponse.java, backend/src/test/java/com/staccato/fixture/moment/MomentDetailResponseFixture.java, backend/src/test/java/com/staccato/moment/controller/MomentControllerTest.java
- #427
- 안드로이드 요청으로 스타카토 조회 API 응답에 추억 기간을 포함하도록 수정했습니다.
=> refactor: 스타카토 조회 API 응답에 추억 기간 추가 #427

android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/common/LocationPermissionManager.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/common/location/LocationDialogFragment.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/main/MainActivity.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/main/viewmodel/SharedViewModel.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/momentcreation/MomentCreationActivity.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/visitupdate/VisitUpdateActivity.kt
- #416 
<br>
> 스타카토 생성 및 수정 화면에 위치 설정 확인 플로우를 추가하고 기존의 위치 권한을 확인하는 플로우를 수정했습니다.
> 위치 설정 및 위치 권한 설정과 관련된 중복 로직들을 `LocationPermissionManager`가 가지도록 변경했습니다.
- **스타카토 생성 화면**
https://github.com/user-attachments/assets/296d96ec-c88a-424e-b049-fddf3c9d1075
- 스타카토 생성 화면은 현위치를 바로 불러옵니다.
- 따라서 화면에 진입하자마자 위치 설정과 위치 권한 설정을 확인 합니다. 
- 위치 권한이 설정 되어있지 않다면 교육용 UI를 띄웁니다.
- 사용자가 교육용 UI의 취소 버튼을 누르면 현 위치를 불러오지 않습니다.
- 사용자가 현위치 불러오기 버튼을 다시 누르면 교육용 UI를 띄워 설정으로 이동하도록 유도합니다.
- 사용자가 설정으로 이동해 위치 권한을 허용하고 돌아오면 바로 현위치를 불러옵니다.
- **스타카토 수정 화면**
https://github.com/user-attachments/assets/4f4ecced-2263-4831-be61-e3f8392eac14
- 스타카토 수정 화면은 현위치 불러오기 버튼을 눌렀을 때만 위치 설정과 위치 권한 설정을 확인합니다.
- 현위치 불러오기 버튼이 눌렸을 때 위치 권한이 허용되어 있다면 현위치를 불러옵니다.
- 현위치 불러오기 버튼아 눌렸을 때 위치 권한이 허용되어있지 않다면 교육용 UI를 띄웁니다.
- 사용자가 설정으로 이동해 위치 권한을 허용하고 돌아오면 바로 …
=> feat: 스타카토 생성 및 수정 화면 위치 권한 플로우 변경 #416

backend/src/main/java/com/staccato/auth/service/AuthService.java, backend/src/main/java/com/staccato/config/auth/AdminProperties.java
- #424
- 이전 기록을 불러올 수 있는 방법이 생겼기 때문에, 더이상 개발용 계정 접속을 위한 로직이 필요 없어졌다.
=> feat: 개발용 이스터에그 로직 제거 #424

android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/momentcreation/MomentCreationActivity.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/momentcreation/adapter/PhotoAttachAdapter.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/momentcreation/adapter/PhotoAttachViewHolder.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/momentcreation/viewmodel/MomentCreationViewModel.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/visitcreation/adapter/AttachedPhotoItemTouchHelperCallback.kt, android/Staccato_AN/app/src/main/res/values/strings.xml
- #441
AttachedPhotoViewHolder에서 onStartDrag 메서드를 구현하고 있어
AttachedPhotoItemTouchHelperCallback의 아래 메서드가 동작하고 있지 않았습니다.
```kotlin
override fun isLongPressDragEnabled(): Boolean {
return true
}
```
따라서 해당 구현을 삭제해 주었습니다.
구글 장소 검색창 클릭 시 `AutocompleteSupportFragment`로 focus가 이동합니다.
따라서 `StaccatoCreationActivity로` 돌아왔을 때 onResume이 호출되며 다시 현위치를 불러오는 버그가 발생했습니다.
MomentCreationViewModel에 isPlaceSearchClicked 변수를 추가해 해결했습니다.
interface `ItemDragListener`에서 `fun onStartDrag(viewHolder: RecyclerView.ViewHolder)` 제거하기
=> fix & feat: 스타카토 생성 시 현주소 로딩 버그 수정 & 사진 길게 눌러 순서 변경 기능 #441

android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memoryupdate/viewmodel/MemoryUpdateViewModel.kt
- #447 
<br>
https://github.com/user-attachments/assets/c732e408-d0f0-4fbc-9181-9fa9e764da3d
<br>
- 추억 수정 시 사진 등록 중에 저장 버튼이 활성화되어 있는 문제 해결  
- 관련 QA 내용
=> fix: 추억 수정 시 사진 등록 중이라면 저장 버튼을 비활성화 #447

android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/momentcreation/CurrentLocationHandler.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/momentcreation/MomentCreationActivity.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/momentcreation/adapter/PhotoAttachViewHolder.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/momentcreation/viewmodel/MomentCreationViewModel.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/visitcreation/adapter/AttachedPhotoItemTouchHelperCallback.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/visitupdate/VisitUpdateActivity.kt, android/Staccato_AN/app/src/main/res/layout/activity_visit_creation.xml, android/Staccato_AN/app/src/main/res/layout/activity_visit_update.xml
=> fix: 현주소 로딩 버그 수정, 사진 드래그 시 투명하게 조절 #444

android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memoryupdate/viewmodel/MemoryUpdateViewModel.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/mypage/MyPageActivity.kt, android/Staccato_AN/app/src/main/res/values/strings.xml
- #448 
https://github.com/user-attachments/assets/a4b16fbc-53cb-40f0-bbac-6dad18708f08
안드로이드 API 레벨 13 이상 부터는 클립보드 복사 시에 시스템에서 토스트 메시지를 띄워줍니다.
즉, API 레벨 13 미만에서는 토스트 메시지가 뜨지 않습니다.
- 바텀시트 너머로 마이페이지 버튼이 눌리는 현상 개선
=> refactor: 클립보드 복사 시 토스트 메시지가 뜨지 않는 문제 해결 #448

.github/workflows/backend-ci-cd-prod.yml
- #437
- 이슈(#437)에서 nginx를 제거하려 했습니다.
- 후에 무중단 배포에서 nginx를 활용할 수도 있어서 우선 그대로 두기로 결정했습니다.
- 이에 따라 변경했던 docker 포트 포워딩 CICD Workflow를 복구했습니다.
=> fix: 운영 서버 docker 포트 포워딩 복구

backend/src/main/java/com/staccato/comment/repository/CommentRepository.java, backend/src/main/java/com/staccato/memory/domain/Memory.java, backend/src/main/java/com/staccato/memory/repository/MemoryMemberRepository.java, backend/src/main/java/com/staccato/memory/service/MemoryService.java, backend/src/main/java/com/staccato/moment/domain/MomentImages.java, backend/src/main/java/com/staccato/moment/repository/MomentImageRepository.java, backend/src/main/java/com/staccato/moment/repository/MomentRepository.java, backend/src/main/java/com/staccato/moment/service/MomentService.java, backend/src/test/java/com/staccato/comment/repository/CommentRepositoryTest.java, backend/src/test/java/com/staccato/fixture/comment/CommentFixture.java, backend/src/test/java/com/staccato/memory/repository/MemoryMemberRepositoryTest.java, backend/src/test/java/com/staccato/moment/repository/MomentImageRepositoryTest.java, backend/src/test/java/com/staccato/moment/repository/MomentRepositoryTest.java
- #406 
- Member 찾는 쿼리 1 → MemberRepository.findById
- Memory 찾는 쿼리 1 → MemoryRepository.findById
- Memory에서 Memory_Member LazyLoading 쿼리 1
- 하나의 Memory에는 하나의 멤버가 연관이 되어있어서 항상 쿼리가 1가 나가게 된다.
`MomentRepository.deleteAllByMemoryId 발생`
- moment에서 해당하는 memory 찾는 쿼리 1
- 찾은 moment 마다 comment 조회, moment_image 조회 쿼리
- 그리고 조회된 모든 것들마다 개별적으로 delete 쿼리
- comment 삭제 → moment_image 삭제(comment 와 moment_image 삭제 순서는 랜덤) → moment 삭제 → memory_member 삭제 → memory 삭제 순서로 진행.(memory 삭제는 `MomentRepository.deleteAllByMemoryId`에서 발생하는 것이 아닌 `MemoryRepository.deleteById` 에서 발생된 것!)
예를 들어 moment가 10개, moment 하나 당comment가 10개, 이미지가 5개라고 한다면
- 모든 moment 를 조회하는 쿼리 1개
- 특정 moment에서 모든 comment 조회하는 쿼리 10개
- 특정 moment에서 모든  moment_image 조회하는 쿼리 10개
- comment 삭제 쿼리 10(moment 수) X 10(comment 수) = 100개
- 이미지 삭제 쿼리 …
=> feat: Bulk Delete 적용 #406

backend/src/main/java/com/staccato/memory/repository/MemoryMemberRepository.java, backend/src/main/java/com/staccato/memory/service/MemoryService.java, backend/src/main/java/com/staccato/moment/repository/MomentRepository.java, backend/src/test/java/com/staccato/memory/repository/MemoryMemberRepositoryTest.java, backend/src/test/java/com/staccato/memory/service/MemoryServiceTest.java, backend/src/test/java/com/staccato/moment/repository/MomentRepositoryTest.java
- #486 
- 추억 조회
- 추억 삭제
- 조회가 이루어지는 이유는 deleteAll()로 판명
- 이는 N+1 문제보다는 BulkDelete를 적용하지 않은 상태에서 발생하는 문제로 판명
- #487 
- 추억 목록 조회
- 특정 날짜를 포함하는 사용자의 모든 추억 목록 조회
- 자세한 사항은 노션 확인 바랍니다.
=> refactor: N+1 문제 해결 #486

backend/src/main/java/com/staccato/auth/service/AuthService.java, backend/src/main/java/com/staccato/memory/domain/Memory.java, backend/src/test/java/com/staccato/auth/service/AuthServiceTest.java
- #508 
- `Memory` 도메인에 기본 추억을 제공하는 정적 팩터리 메서드 `basic()`을 만들었습니다.
- 기본 추억은 `기본 추억`이라는 제목과 `스타카토를 추억에 담아보세요`라는 설명을 가집니다.
- `AuthService`에서는 `login()`이 호출되었을 때 회원 정보를 생성하고, 해당 회원 정보에 대해 기본 추억을 생성합니다.
=> feat: 기본 추억 제공 구현 #508

.github/workflows/android-cd.yml, .github/workflows/android-ci-cd-dev.yml, .github/workflows/android-ci.yml
- #445 
브랜치 전략이 변경됨에 따라, **CI** 가 적용될 브랜치를 업데이트 하였습니다.
데모(테스트)용 앱을 추출하기 위해 사용 중이던 **CI/CD**를 수정하였습니다. 
- yml 파일 명 변경 : 개발 단계에서 사용되는 CI/CD 파일이므로, 파일 이름을 명시적으로 변경하였습니다.
- 타겟 브랜치 변경 : 개발 브랜치인 `develop` 에서 배포 준비 브랜치인 `release-an`으로 push 될 때 **CI/CD** 가 적용됩니다.
- 앱 빌드 모드 변경 : 무거운 debug 용으로 빌드하지 않고, 용량이 더 적은 release 모드로 빌드하도록 변경하였습니다.
이전에 CD 설정을 할 때, 콘솔로 업로드하는 작업이 인증 오류로 업로드가 되지 않는 문제가 있었습니다.
기존에 가지고 있던 서비스 계정 키 Secret 변수에 문제가 있을 것이라 생각해서, 새로 생성한 서비스 계정의 키로 교체하였습니다.
CD를 재설정하는 작업을 아래와 같이 진행했습니다.
- 구글 플레이 콘솔에 업로드하는 작업 복구
- CI, CD 의 동작을 잘 모르겠다면 언제든 질문해주세요!
- 자동 배포 잘되게 빌기
=> build: 안드로이드 CI/CD 재설정 #445

android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/timeline/TimelineFragment.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/timeline/adapter/TimelineAdapter.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/timeline/model/SortType.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/timeline/viewmodel/TimelineViewModel.kt, android/Staccato_AN/app/src/main/res/menu/menu_sort.xml, android/Staccato_AN/app/src/main/res/values/strings.xml
- #503
<br>
https://github.com/user-attachments/assets/962470c5-ec04-4d94-a7b5-6a741e4eb546
<br>
<br>
**정렬 타입 enum class**
- `enum class`를 활용해 사용자가 선택한 정렬 메뉴에 해당하는 동작을 `view model`이 결정할 수 있도록 구현했습니다.
```kotlin
enum class SortType(
@MenuRes val menuId: Int,
) {
CREATION(R.id.creation_order),
LATEST(R.id.latest_order),
OLDEST(R.id.oldest_order),
WITH_PERIOD(R.id.with_period_order),
WITHOUT_PERIOD(R.id.without_period_order),
...
;
companion object {
fun from(menuId: Int): SortType = entries.first { it.menuId == menuId }
}
}
```
**최신 순 정렬**
- `sortedByDescending()`을 활용했습니다.
**과거 순 정렬**
- `sortedWith()`을 활용했습니다.
- `startAt`을 비교해 오름차순으로 정렬하고 `startAt`이 null인 추억들은 `nullsLast()`를 이용해 기간이 있는 추억들 뒤쪽에 위치하도록 구현했습니다.
```kotlin
fun sortByOldest() {
val memoriesSortedByOldest = …
```
=> feat: 나의 추억들 정렬 기능 구현 #503

backend/src/main/resources/application-prod.yml
- #517 
- MaxThread
- 크기가 크면 크면 context Switching 비용이 많이 발생한다.
- 스레드도 메모리를 들고 있는다!
- 값을 줄이면서 테스트 했을 때 **30**일 때가 제일 TPS가 좋았다.
- MaxConnection
- 1000명 기준 목표 TPS가 40인 것에 비해 Max Connection이 과도하게 크다.
- Connection을 획득 후 대기만 하면서 리소스가 낭비된다.
- 따라서, Max Connection 수가 더 줄었을 때 성능은 더 향상된다.
- 대신, connection을 얻지 못해서 테스트 실패율이 증가한다.
- 테스트 실패율과 TPS를 두고 저울질 한다면, 테스트 실패율이 더 낮은 것이 중요하다고 생각해서 **2048**을 선택했다.        
- Worker Connection
- nginx에서 동시에 처리할 수 있는 커넥션 수
- WorkerConnection ≥ MaxConnection으로 설정을 하는 것이 좋다고 생각했다.
- MaxConnection의 수와 같이 **2048**개의 동시 처리 커넥션 수를 가져가기로 했다.
- Min Spare
- 항상 있는 최소한의 스레드 수
- 너무 낮게 설정하면 커넥션이 즉시 사용 가능한 상태가 아니어서 추가 요청 시 지연이 발생할 수 있고, 너무 높게 설정하면 불필요한 커넥션 유지로 자원 낭비가 발생할 수 있다
- 10개나 20개나 메모리 부하에 큰 영향을 미칠까? 성능에 큰 영향을 미칠까?
- 큰 영향을 끼치지 않는다고 판단하여 **수정하지 않기로(10)** 결정했다.
- accept-count
- …
=> chore: Thread, Hikari CP 변경

backend/src/main/java/com/staccato/auth/service/AuthService.java, backend/src/main/java/com/staccato/memory/domain/Memory.java, backend/src/test/java/com/staccato/memory/domain/MemoryTest.java
- #530 
- 기본 추억의 제목을 '기본 추억'에서 멤버 이름을 사용해서 '{멤버 이름}의 추억'으로 바꾸었습니다.
=> feat: 기본 추억 제목 변경 #530

android/Staccato_AN/app/build.gradle.kts, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/main/MainActivity.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/main/viewmodel/SharedViewModel.kt
- #533 
- 스타카토 삭제 시 마커가 갱신되지 않는 오류 해결
스타카토 삭제 후 마커가 제대로 갱신되는 지 확인해주세요!
=> fix: 스타카토 삭제 시 마커가 갱신되지 않는 오류 해결 #533

android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/common/PhotoAttachFragment.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/StaccatoCreationActivity.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/viewmodel/StaccatoCreationViewModel.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatoupdate/StaccatoUpdateActivity.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatoupdate/viewmodel/StaccatoUpdateViewModel.kt, android/Staccato_AN/app/src/main/res/values/strings.xml
- #536
|ACTION_PICK_IMAGES|ACTION_PICK_IMAGES(사진 수 경고)|앨범|
|---|---|---|
|<img src="https://github.com/user-attachments/assets/e2c5f20c-7a88-4a46-85a8-0c2809aae50a" width="230" />|<img src="https://github.com/user-attachments/assets/2d8554c8-4f97-418d-958f-cd0c4f4d0a65" width="230" />|<img src="https://github.com/user-attachments/assets/c1103c26-a907-4949-8ad2-7898063ef3ae" width="230" />|
티라미수 이상 버전에서는 권한이 없어도 `MediaStore.ACTION_PICK_IMAGES`로 기기의 사진 파일에 접근 가능합니다.
해당 작업으로 얻을 수 있는 이점은 다음과 같습니다.
1. **권한이 없어도 사진**을 불러올 수 있음. (권한이 있다면 그대로 앨범으로 접근)
2. `MediaStore.ACTION_PICK_IMAGES`에서 **선택 가능한 사진 장 수 제한 가능**
---
* 버그 영상
https://github.com/user-attachments/assets/d097749d-3a66-4091-b9eb-c6f6d6255fe4
코루틴 Job은 취소 시 내부의 중단 가능 지점(suspend fun)에서 `JobCancellationException`를 발생시킵니다.
직전의 네트워크 에러 핸들링 …
=> feat & fix: 사진 코루틴 취소 버그 수정 / ACTION_PICK_IMAGES 적용 #536

backend/src/main/java/com/staccato/comment/controller/CommentController.java, backend/src/main/java/com/staccato/comment/controller/docs/CommentControllerDocs.java, backend/src/test/java/com/staccato/comment/controller/CommentControllerTest.java
- #544 
- `PUT/DELETE /v2/comments/{commentId}`형태의 API로 버저닝하였습니다.
- comments를 필터링하는 것이 아닌 특정 식별자를 가진 자원을 접근하는 것이므로 path varaible 형태를 사용하도록 구현하였습니다.
- 안드로이드 반영
=> refactor: comments api uri 수정 #544

android/Staccato_AN/app/src/main/java/com/on/staccato/data/comment/CommentApiService.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/data/dto/comment/CommentRequest.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/data/dto/mapper/CommentMapper.kt
- #560 
기존 댓글 수정, 삭제( `PUT` , `DELETE` ) API의 URI가 `Query String` 에서 `Path Variable` 형태로 변경되었습니다.
- `Query String` : `"/comments?commentId={commentId}"` 형태
- `GET` 요청 등 주로 데이터 조회 API에서 활용
- `Path Variable` : `"/comments/{commentId}"` 형태
- `POST`, `PUT`, `DELETE` 등 주로 데이터 수정, 삭제 API에서 활용
**변경 사항**
```kotlin
// 예시
@DELETE("comments/v2/{commentId}")
suspend fun deleteComment(
@Path("commentId") commentId: Long,
): Response<Unit>
```
- 변경된 URI로 댓글 기능이 잘 동작하는걸 확인했습니다.
- URI 리팩터링이 잘 이루어졌는지 확인해주세요.
추후에 버저닝 제거하기
=> refactor: comment API의 URI 수정 #560

android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/StaccatoCreationActivity.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/adapter/AttachedPhotoItemTouchHelperCallback.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/adapter/ItemDragListener.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/adapter/PhotoAttachAdapter.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatoupdate/StaccatoUpdateActivity.kt
- #588 
출시하고 2달 동안 그 누구도 알아채지 못한 버그..
이스터 에그라고 우기고 싶은 버그..
를 발견해서 후딱 고쳐보았습니다.
위 사진에서 동그라미 친 버튼을 꾹 누르면 액티비티가 종료됩니다.
AttachedPhotoItemTouchHelperCallback 클래스에서 타입 캐스팅 예외가 일어나고 있습니다.
```
java.lang.ClassCastException: com.on.staccato.presentation.staccatocreation.adapter.PhotoAttachViewHolder$AddPhotoViewHolder
cannot be cast to
com.on.staccato.presentation.staccatocreation.adapter.PhotoAttachViewHolder$AttachedPhotoViewHolder
```
```kotlin
// AttachedPhotoItemTouchHelperCallback.kt
override fun onSelectedChanged(
viewHolder: RecyclerView.ViewHolder?,
actionState: Int,
) {
super.onSelectedChanged(viewHolder, actionState)
when (actionState) {
ItemTouchHelper.ACTION_STATE_DRAG -> {
if (viewHolder != null) {
(viewHolder as PhotoAttachViewHolder.AttachedPhotoViewHolder).startMoving() // -> 해당 …
```
=> fix: 사진 첨부를 길게 터치할 시 액티비티가 종료되는 버그 (스타카토 생성/수정 화면) #588

.github/workflows/backend-ci-cd-multi-prod.yml
- #565 
- DEV환경 EC2내부에 아래와 같이 쉘 스크립트를 미리 지정
>xxx-origin으로 표현된 쉘 스크립트는 해당 변경작업 전에 구성되었던 것입니다
우선은 새로운 workflow를 생성하여 테스트를 진행하는 것으로 구성하였습니다!
변경사항들에 대한 기록은 노션페이지를 참고해주시면 감사하겠습니다
=> chore: 무중단 배포 Workflow 전략 수정 #565

android/Staccato_AN/app/src/main/res/values/strings.xml
- #578 
- 도메인명 변경에 따라 UI 상에 보여지는 추억이라는 단어를 카테고리로 수정했습니다.
- 추억이 카테고리로 변경되지 않은 부분이 있다면 알려주세요!
=> ui: 도메인명 변경에 따라 추억을 카테고리로 수정 #578

backend/src/main/resources/static/index.css, backend/src/main/resources/templates/index.html
- #597 
- 휴대폰 화면에서도 어색하게 표시되지 않도록 반응형 디자인을 개선했습니다.
=> refactor: 화면에 반응형 디자인 적용 #597

.github/workflows/backend-ci-cd-dev.yml, .github/workflows/backend-ci-cd-multi-dev.yml, backend/src/main/java/com/staccato/auth/service/dto/request/LoginRequest.java, backend/src/main/java/com/staccato/memory/service/MemoryFilter.java, backend/src/main/java/com/staccato/memory/service/dto/request/MemoryReadRequest.java, backend/src/test/java/com/staccato/memory/service/MemoryFilterTest.java, backend/src/test/java/com/staccato/memory/service/MemorySortTest.java, backend/src/test/java/com/staccato/memory/service/dto/request/MemoryReadRequestTest.java
- #546 
- #604 
- 필터링 API 에서 필터링 조건 없을 때 NPE에 대한 고려를 놓쳤습니다.
- 컨트롤러 단위 테스트와 도메인 단위 테스트로는 잡지 못했어요! dto 내부에 해당 로직이 있기 때문에 dto 단위 테스트가 필요하다고 생각해서 추가했습니다.
- 추가로, 같은 조건값이 들어왔을 때에는 한 번만 카운트 하도록 로직 추가했습니다.
- Dev 서버의 workflow가 2개가 있어서 하나는 비활성화했습니다~
=> fix: 필터링 API 파싱 오류 수정 #604

backend/src/main/java/com/staccato/memory/controller/CategoryController.java, backend/src/main/java/com/staccato/memory/controller/CategoryDtoMapper.java, backend/src/main/java/com/staccato/memory/controller/docs/CategoryControllerDocs.java, backend/src/main/java/com/staccato/memory/service/dto/request/CategoryReadRequest.java, backend/src/main/java/com/staccato/memory/service/dto/request/CategoryRequest.java, backend/src/main/java/com/staccato/memory/service/dto/response/CategoryDetailResponse.java, backend/src/main/java/com/staccato/memory/service/dto/response/CategoryIdResponse.java, backend/src/main/java/com/staccato/memory/service/dto/response/CategoryNameResponse.java, backend/src/main/java/com/staccato/memory/service/dto/response/CategoryNameResponses.java, backend/src/main/java/com/staccato/memory/service/dto/response/CategoryResponse.java, backend/src/main/java/com/staccato/memory/service/dto/response/CategoryResponses.java, backend/src/main/java/com/staccato/memory/service/dto/response/StaccatoResponse.java, backend/src/main/java/com/staccato/moment/controller/StaccatoController.java, backend/src/main/java/com/staccato/moment/controller/StaccatoDtoMapper.java, backend/src/main/java/com/staccato/moment/controller/docs/StaccatoControllerDocs.java, backend/src/main/java/com/staccato/moment/service/dto/request/StaccatoRequest.java, backend/src/main/java/com/staccato/moment/service/dto/response/StaccatoDetailResponse.java, backend/src/main/java/com/staccato/moment/service/dto/response/StaccatoIdResponse.java, backend/src/main/java/com/staccato/moment/service/dto/response/StaccatoLocationResponse.java, backend/src/main/java/com/staccato/moment/service/dto/response/StaccatoLocationResponses.java, backend/src/test/java/com/staccato/memory/controller/CategoryControllerTest.java, backend/src/test/java/com/staccato/memory/service/dto/request/CategoryReadRequestTest.java, backend/src/test/java/com/staccato/memory/service/dto/request/CategoryRequestTest.java, backend/src/test/java/com/staccato/moment/controller/StaccatoControllerTest.java
- #594 
- 도메인명 변경
- `memory` -> `category`
- `moment` -> `staccato`
- 수정한 부분
- client의 원활한 작업을 위해 빠른 변경이 필요해서, controller 부분만 변경했습니다.
- `controller`, `dto`, `swagger`, `test`
* 코드의 충돌과 기존 API 삭제의 어려움을 최소화하고자, 전부 새로운 파일을 만들어 수정했습니다.
* Dto 변경에 따른 서비스 클래스로의 변경 전파를 막기 위해, 서비스와 컨트롤러 사이에 `DtoMapper` 클래스를 만드는 방식으로 구현했습니다.
* memory 및 moment와 관련된 controller, dto, swagger, test 파일 삭제
파일을 복사해서 고치는 방식으로 했고 테스트도 전부 구현했기 때문에 큰 문제가 없을 것으로 예상됩니다.
눈으로 코드 전부를 따라가며 코드 리뷰하는 것은 어려움이 있을 것 같아, 
pull 받아서 swagger를 확인해보는 방법이 리뷰 과정에 도움이 될 것 같습니다.
나중에 `도메인명 변경` 작업에서 이어서 할 부분
* DB 스키마 변경
* `service`, `repository`, `domain` 변경
=> refactor: 도메인명 변경 (memory -> category, moment -> staccato) #594

backend/src/main/java/com/staccato/moment/controller/StaccatoDtoMapper.java
- #606 
- 스타카토 조회 API 응답의 스타카토 ID와 카테고리 ID 응답값 매핑이 잘못되어 있어 수정했습니다.
- StaccatoDtoMapper와 CategoryDtoMapper에 오류가 없는지 체크했습니다. 놓친 부분이 있을지도 모르니 더블 체크 부탁드립니다.
- @hxeyexn @s6m1n @Junyoung-WON 조만간 바뀔 코드라서 테스트가 따로 없습니다. 체크하긴 했지만, 도메인명이 바뀐 API (Category, Staccato)에서 문제가 있는 것 같다면 백엔드 파트도 콜해주세용!
=> fix: 스타카토 조회 API 응답값 매핑 오류 수정 #606

backend/src/main/java/com/staccato/comment/controller/CommentController.java, backend/src/main/java/com/staccato/comment/service/dto/request/CommentRequestV2.java, backend/src/test/java/com/staccato/comment/controller/CommentControllerV2Test.java
- #609 
* `POST /comments`에서 사용하는 `CommentRequest` 내부에 `momentId`가 있음
-> `staccatoId`를 사용하는 새로운 `CommentRequestV2` Dto 생성
-> `CommentRequestV2`를 사용하는 `POST /comments/v2` 생성
* `GET /comments`의 `RequestParam`에 `momentId`가 있음
-> `staccatoId`를 사용하는 `GET /comments/v2` 생성
* 테스트는 하나의 파일에서 만들려다가 테스트 데이터 구성에 복잡함을 느껴서, 구현의 편리성을 위해 다른 파일로 분리해서 작업했습니다.
* 클라이언트에서 새로운 API 적용 완료 후, 구 버전 API 제거 필요
=> fix: Comment API에서 도메인명 안바뀐 부분 수정 #609

backend/src/main/resources/error-appender.xml, backend/src/main/resources/info-appender.xml, backend/src/main/resources/logback-spring.xml, backend/src/main/resources/warn-appender.xml
- #590 
- 로그 저장 기간을 15일에서 365일(1년)으로 변경했습니다.
- `<totalSizeCap>3GB</totalSizeCap>` 설정 때문에 전체 로그파일의 크기가 3GB를 넘어가면 오래된 로그부터 자동으로 삭제됩니다. 따라서 로그 저장 기간이 길어도 용량 문제가 생기지 않습니다.
- 오늘 일자의 로그를 임시로 저장하는 파일의 이름을 `info.log` `warn.log` `error.log`로 변경했습니다.
=> fix: LogBack appender xml 수정 #590

backend/src/main/java/com/staccato/config/log/ReadAllCategoryMetricsAspect.java, backend/src/main/java/com/staccato/memory/controller/CategoryController.java, backend/src/main/java/com/staccato/memory/service/MemoryFilter.java, backend/src/main/java/com/staccato/memory/service/MemorySort.java, backend/src/test/java/com/staccato/config/log/ReadAllCategoryMetricsAspectTest.java
- #601 
- AOP를 사용하여 `MemoryService.readAllMemories` 메서드 호출이 성공하였을 때(`@AfterReturning`) 정렬 조건과 필터링 조건에 대한 메트릭을 기록하도록 구현했습니다.
- `Counter`를 활용하여 각 정렬 조건과 필터링 조건의 사용 횟수를 메트릭으로 기록하고 있습니다.
- 관련 테스트 함께 구현했습니다.
=> feat: 필터링/조건 옵션 로깅 구현 #601

backend/src/main/java/com/staccato/config/log/CreateMomentMetricsAspect.java, backend/src/test/java/com/staccato/config/log/CreateMomentMetricsAspectTest.java, backend/src/test/java/com/staccato/fixture/memory/MemoryFixture.java
- #611]
- 코드를 단순히 Service 로직에 넣으면 매트릭을 관리하는 로직이 핵심 비즈니스 개발 로직에 침투하는 이유 때문에 AOP를 적용하기로 하였습니다.
공통된 관심사의 분리라는 뜻과는 조금 다르게 하나의 메서드에 대한 적용이여서 AOP 적용이 고민되었지만, 아래 2가지 이유로 인해 Service layer에 AOP를 적용하게 되었습니다.
- 생성로직이 정상 수행된 경우에만 매트릭이 기록되어야 한다. 따라서 컨트롤러가 아닌 Service에 적용하여야 한다.
- 비즈니스 로직에 매트릭 기록 로직이 침범하는 것은 옳지 않다.
`staccato` 생성 `api` 한번 호출하고 난 뒤에 `metrics`이 생기게 됩니다.
`local`에서 정상동작함을 확인했습니다.
시간에 따라 분기처리되는 과정으로 인해 제공되는 `@Counted` 를 사용하지 못하고 `Counter Builder`를 통해 구성하게 되었습니다.
=> feat: 기록 시점이 과거 / 현재 / 미래인지 비즈니스 매트릭 구성 #611

android/Staccato_AN/app/proguard-rules.pro
- #637 
<br>
- 코드 난독화 설정으로, 제네릭 타입 Signature가 소거되어 제네릭 타입을 확인할 수 없는 런타임 에러 발생.
- 에러 발생 시점: CallAdapter 반환에 필요한 리턴 타입을 타입 캐스팅 할 때(ApiResultCallAdapterFactory)
- proguard-rules.pro에서 Signature를 소거 대상에서 제외시키는 규칙을 설정하여 문제 해결
<br>
<br>
<br>
=> fix: 코드 난독화 설정으로 인한 제네릭 타입 소거 에러 해결 #637

backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-local.yml, backend/src/main/resources/application-prod.yml, backend/src/test/java/com/staccato/config/log/CreateMomentMetricsAspectTest.java
- #555 
- 아래와 같이 수정하였습니다.
``` java
management:
server:
port: 9292
endpoints:
web:
exposure:
include: info, health, prometheus
jmx:
exposure:
exclude: "*"
endpoint:
health:
show-components: never
```
이슈와 다르게 반영하지 않은 부분은 base url부분인데,
위와 같이 구성하면 기본 애플리케이션 포트(예: 8080)와는 별개로, 관리용 엔드포인트들이 9292번 포트에서 서비스됩니다.
즉, 애플리케이션을 실행하면 일반 웹 요청은 기본 포트에서 처리되고, 관리 요청(health, info, prometheus 등)은 9292번 포트에서 처리됩니다.
따라서 `외부에서의 접근이 가능한가?` 라는 관점으로 봤을 때, base url까지 변경하는 것은 필요하지 않다고 판단하여 수정하지 않았습니다.
=> refactor: Actuator 설정 값 변경 #555

backend/src/main/java/com/staccato/memory/service/MemoryService.java, backend/src/main/java/com/staccato/moment/domain/Moment.java, backend/src/main/java/com/staccato/moment/domain/MomentImages.java, backend/src/main/java/com/staccato/moment/service/MomentService.java, backend/src/test/java/com/staccato/moment/domain/MomentImagesTest.java
- #650 
- 스타카토 수정 시 기존 이미지에 대한 순서 변경이 적용 안되는 이슈를 해결하였습니다.
- 기존 로직보다 쿼리수는 더 나가겠지만, 전체 이미지가 5개로 제한되는 상황이므로 크리티컬하지 않다고 판단하였습니다.
- 이미지의 순서를 부여하는 칼럼을 새롭게 구성하는 방식 또한 고려해보았는데, 새롭게 칼럼을 추가해서 관리하는 것보다 최대 5개의 이미지로 제한되므로 전체 삭제 후 전체 갱신으로 구성하였습니다.
=> fix: 이미지 순서 수정 시 반영 안되는 문제 #650

android/Staccato_AN/app/src/main/java/com/on/staccato/util/logging/Param.kt
- #675
- Param.kt 파일 내부의 이벤트 파라미터 문자열 상수들을 한글에서 영문으로 변경했습니다.
Firebase Analytics에서 확인한 결과 위 사진처럼 **모든 로그에 매개변수 정보가 누락**되어있었습니다.
로깅은 되는데 매개변수 정보가 없는 것에 의문이 들어 adb로 연결해 `tag:FA 로그캣`을 살펴보니 아래와 같은 오류 메시지가 뜨고 있었습니다.
이에 빠르게 한글을 영문으로 변경했고, 그 결과 아래처럼 정상적으로 매개변수 정보도 함께 로깅이 되는 것을 확인했습니다.
```kotlin
// bottom_sheet_state : 바텀 시트 상태, bottom_sheet_state_duration : 유지 시간
Logging event: origin=app,name=bottom_sheet,params=Bundle[{bottom_sheet_state=EXPANDED, ga_event_origin(_o)=app, ga_screen_class(_sc)=MainActivity, ga_screen_id(_si)=-1241891066083350676, bottom_sheet_state_duration=16.844}]
// is_viewed_from_marker_click : 마커 클릭으로 조회된 스타카토인지?
Logging event: origin=app,name=staccato_read,params=Bundle[{ga_event_origin(_o)=app, ga_screen_class(_sc)=MainActivity, ga_screen_id(_si)=-1241891066083350676, …
```
=> fix: Firebase Analytics 이벤트 로깅 시 매개변수 정보 누락 #675

.github/workflows/backend-ci-cd-dev.yml, .github/workflows/backend-ci-cd-multi-dev.yml, .github/workflows/backend-ci-cd-prod.yml, .github/workflows/backend-ci.yml, backend/Dockerfile.dev, backend/Dockerfile.prod, backend/build.gradle, backend/src/main/java/com/staccato/config/JasyptConfig.java, backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-local.yml, backend/src/main/resources/application-prod.yml, backend/src/test/java/com/staccato/config/JasyptConfigTest.java
- #647 
- Github Secrets으로만 관리되던 민감정보들을 jasypt를 활용하는 것으로 변경합니다.
- Github Secrets의 경우 추후에 어떠한 값을 지정했는지 알 수 없는 불편함이 존재합니다.
- submoudle을 사용하였을 때 아래와 같은 단점이 존재합니다.
**Git 워크플로우의 복잡성**
- 서브모듈은 별도의 저장소로 관리되기 때문에 클론, 업데이트, 브랜치 관리 등에서 추가적인 커맨드와 주의가 필요합니다.
**버전 동기화 문제**
- 상위 프로젝트와 서브모듈의 버전이 자동으로 동기화되지 않아, 업데이트 시 별도로 관리해줘야 하며, 이 과정에서 버전 불일치 문제가 발생할 수 있습니다.
`따라서 jasypt를 적용하게 되었습니다.`
- jasypt 빈을 등록하면서 다양한 설정값들이 존재하였는데, 웬만한 부분들은 default로 구성하였습니다.
- pool size와 같은 경우에는 아래를 참고하여 t4g.micro 기준 코어 2개이므로, 2로 설정하였습니다.
http://www.jasypt.org/general-usage.html
- 사용되지 않는 `admin` 관련 환경변수는 삭제했는데, 한번 확인 부탁드려용
=> feat: 민감 정보 jasypt 적용 #647

.github/workflows/android-ci.yml
- #717 
- [Action : Publish Test Results](https://github.com/marketplace/actions/publish-test-results) 을 활용해 테스트 로그를 코멘트로 남깁니다.
- 테스트 실행 명령어 변경
```
./gradlew testDebugUnitTest --stacktrace --no-build-cache --no-parallel
```
- `testDebugUnitTest` : 디버그 모드에서의 테스트만 실행
- `--stacktrace` : 에러 발생 시 디버깅 로그 출력
- `--no-build-cache` : 빌드 캐시 사용하지 않음, 모든 테스트를 새로 실행하여 신뢰도 보장
- `--no-parallel` : 순차적 실행, 간헐적인 에러 발생 방지
- 브랜치 실행 조건 수정
- `release-an`과 `main` 브랜치는 제거했습니다.
- `workflow_dispatch`: base 브랜치에 병합되지 않은 CI 워크플로우를 수동으로 실행할 수 있는 조건입니다.
- 임시로 CI를 수정하고 실행할 수 있습니다(CI 수정사항 반영 전 확인, 임시 디버깅에 용이)
- Build 단계 제거
- test 실행 시 자동으로 build를 진행하기 때문에 Build 단계는 제거하였습니다.
CI가 시간이 오래걸려서, Build 단계를 제거하고 Debug Test만 실행하도록 변경했습니다.
`./gradlew test` ➡️  `./gradlew testDebugUnitTest`
수정 사항이 괜찮은지 확인해주세요!
- `test`: Debug, …
=> build: Android CI 테스트 로깅 출력 #717

backend/src/main/java/com/staccato/web/PageController.java, backend/src/main/resources/static/css/share.css, backend/src/main/resources/static/js/share.js, backend/src/main/resources/templates/share.html, backend/src/test/java/com/staccato/web/PageControllerTest.java
Closes #728 
- 해당 스타카토의 이미지가 있는 경우, 첫 번째 이미지를 링크 썸네일로 띄웁니다.
- 해당 스타카토의 이미지가 없는 경우, 기본 이미지를 링크 썸네일로 띄웁니다.
- 스타카토 이미지에 반응형 디자인 적용
=> feat: 스타카토 공유 링크 썸네일 지정 #728

backend/src/main/java/com/staccato/category/controller/CategoryController.java, backend/src/main/java/com/staccato/category/controller/CategoryControllerV2.java, backend/src/main/java/com/staccato/category/controller/docs/CategoryControllerV2Docs.java, backend/src/main/java/com/staccato/category/service/CategoryService.java, backend/src/main/java/com/staccato/category/service/dto/response/CategoryDetailResponseV2.java, backend/src/main/java/com/staccato/config/OpenApiConfig.java, backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-local.yml, backend/src/main/resources/application-prod.yml, backend/src/test/java/com/staccato/category/controller/CategoryControllerTest.java, backend/src/test/java/com/staccato/category/controller/CategoryControllerV2Test.java, backend/src/test/java/com/staccato/category/service/CategoryServiceTest.java
- #741 
- 카테고리 수정 시 특정 카테고리 조회 API를 이용하여 기존 정보를 불러옵니다.
- 따라서, 수정 시 색상 수정을 위해서는 특정 카테고리 조회 API에서도 색상 응답 필드가 필요하여 이를 추가한 V2 를 구현했습니다.
=> feat: 특정 카테고리 조회 시 색상 응답 필드를 포함하는 API V2 구현 #741

backend/src/main/resources/static/css/share.css, backend/src/main/resources/static/js/share.js, backend/src/main/resources/templates/share.html
- #745 
* 사진 없을 때 빈 공간 축소
* 이모지 확대 기능 삭제
* 기본 이미지 크기 축소 (0.8배)
* 기분 문구 왼쪽 정렬
* 코멘트 없을때 문구 수정 (아직 코멘트가 없어요!)
* 홍보 위쪽 문구 삭제 (더 많은 추억을 남기고 싶다면?)
=> refactor: 스타카토 공유 페이지 디자인 수정 #745

backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-local.yml, backend/src/main/resources/application-prod.yml
- #744 
- #750 
- P99는 꼭대기 부하 구간에서 얼마나 느린 요청이 있는지를 보여줌
- 평균이나 중앙값은 극단적인 outlier를 반영하지 않아 성능 문제를 숨길 수 있기에 P99를 적용
- Spring Boot Trace 생성 및 OTLP 전송 설정
exporter endpoint의 암호화 전 값은 노션에 있습니다.
=> feat: P99 latency 적용 + Spring Boot OTLP 설정 #744

backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-prod.yml
- #754 
- Grafana에서 Trace의 데이터를 읽을 수 있도록, `service.name`을 명시했습니다.
- dev와 prod의 Trace를 구분할 수 있도록, 환경을 명시해주었습니다.
=> feat: Grafana에서 trace 검색 가능하게 하기 #754

android/Staccato_AN/app/build.gradle.kts, android/Staccato_AN/gradle/libs.versions.toml
- #796 
<br>
새로운 기능을 Compose로 구현하기 위해 Jetpack Compose 의존성을 추가했습니다.
- Jetpack Compose 의존성 추가
- Compose Material Design3 의존성 추가
- Preview 의존성 추가
- Jetpack Compose UI Test 의존성 추가
<br>
[Compose to Kotlin Compatibility Map](https://developer.android.com/jetpack/androidx/releases/compose-kotlin#pre-release_kotlin_compatibility)
<br>
Kotlin `1.9.0`에 호환되도록 Compose Compiler Version을 `1.5.2`로 설정했습니다.
```kotlin
composeOptions {
kotlinCompilerExtensionVersion = "1.5.2"
}
```
<br>
추가로 필요한 의존성이 있는지 확인해 주세요!
공동 카테고리 기능 구현을 위해 빠른 리뷰 부탁드립니다~
<br>
=> build: Jetpack Compose 의존성 추가 #796

android/Staccato_AN/app/src/main/java/com/on/staccato/theme/Typography.kt
- #809
<br>
- Compose용 Typography 추가
<br>
`사용 방법`
```kotlin
@Composable
fun TextComponent(
modifier: Modifier = Modifier,
color: Color = StaccatoBlack,
description: String,
style: TextStyle,
) {
Text(
text = description,
modifier = modifier,
style = style,
color = color
)
}
@Preview(showBackground = true)
@Composable
private fun TextPreview() {
// style에 정의된 typography 설정
TextComponent(modifier = Modifier, description = "Compose 🚀", style = body1)
}
```
<br>
Compose app’s theme의 Typography를 사용하면 기존 typography를 사용하기엔 제약이 있어서 style만 정의했습니다!
또한 color는 자유롭게 설정할 수 있도록 Style에 설정하지 않았습니다.
<br>
=> ui: Compose용 Typography 추가 #809

android/Staccato_AN/app/src/main/res/values/strings.xml
- #807 
<br>
닉네임 입력 형식 피드백 문구에 띄어쓰기가 누락되어 있었습니다. 문구를 아래와 같이 변경했습니다.
- `닉네임은 한글, 영어, 숫자, 띄어쓰기,\n마침표(.), 밑줄(_)만 사용할 수 있어요.`
| 변경 전 | 변경 후 |
|---|---|
| ![image](https://github.com/user-attachments/assets/7df7fb0e-b795-4806-9ded-689091e75525) | ![image](https://github.com/user-attachments/assets/2f0ce384-01e6-4603-a7dc-5dead99fe829) |
<br>
- 이번 주 배포에 함께 적용하려 합니다!
<br>
- 새 기능 컴포즈 열심히~
=> fix: 닉네임 입력 형식 피드백 문구 수정 #807

backend/src/main/java/com/staccato/member/controller/MemberController.java, backend/src/main/java/com/staccato/member/repository/MemberRepository.java, backend/src/main/java/com/staccato/member/service/MemberService.java, backend/src/main/java/com/staccato/member/service/dto/response/MemberResponses.java, backend/src/test/java/com/staccato/member/controller/MemberControllerTest.java, backend/src/test/java/com/staccato/member/service/MemberServiceTest.java
- #815 
- 닉네임으로 사용자 목록을 검색합니다.
- `GET /members/search?nickname={}`
- 응답으로 반환하는 사용자 목록의 사용자 정보는 식별자, 닉네임, 프로필 이미지 경로를 포함합니다.
- 검색한 사용자 중 이미 카테고리에 포함된 사용자 여부를 판단하는 필드를 추가하는 것은 REST하지 않다고 생각이 들었습니다. 따라서, 특정 카테고리에 포함된 사용자 목록 조회 API(이어서 구현 예정)와 닉네임으로 사용자 목록 검색 API를 함께 사용하여 클라이언트 측에서 이미 카테고리에 포함된 사용자를 판단하는 방식이 적합하다고 생각했습니다. 다른 분들의 의견도 궁금해요!
=> feat: 닉네임으로 사용자 목록 검색 API 구현 #815

.github/workflows/android-ci.yml
- #826 
- 안드로이드 CI 워크플로에서 UI Test가 영구적으로 실행되는 오류를 해결합니다.
- 테스트가 끝났음에도 특정 기기의 AVD가 종료되지 않고 Step이 무한히 실행 중인 에러가 자주 발생했습니다.
- 또한 특정 기기에서 UI 테스트의 실패도 잦았습니다.
- 이에 캐싱 사용이 문제 원인일 것이라 추측하여 캐싱을 사용하는 step을 제거하였습니다.
해당 PR의 워크플로가 잘 동작하는지 확인해주세요!
- 문제 없이 CI 적용하기
- 열린 PR 리뷰하기
=> fix: 안드로이드 CI UI Test 영구 실행 오류 #826

backend/src/main/java/com/staccato/category/controller/CategoryController.java, backend/src/main/java/com/staccato/category/controller/CategoryControllerV2.java, backend/src/main/java/com/staccato/category/controller/CategoryControllerV3.java, backend/src/main/java/com/staccato/category/controller/docs/CategoryControllerV3Docs.java, backend/src/main/java/com/staccato/category/domain/Category.java, backend/src/main/java/com/staccato/category/service/CategoryService.java, backend/src/main/java/com/staccato/category/service/dto/response/CategoryDetailResponseV3.java, backend/src/main/java/com/staccato/category/service/dto/response/CategoryResponseV3.java, backend/src/main/java/com/staccato/category/service/dto/response/CategoryResponsesV2.java, backend/src/main/java/com/staccato/category/service/dto/response/CategoryResponsesV3.java, backend/src/main/java/com/staccato/config/OpenApiConfig.java, backend/src/main/java/com/staccato/config/swagger/SwaggerExamples.java, backend/src/main/java/com/staccato/staccato/repository/StaccatoRepository.java, backend/src/test/java/com/staccato/category/controller/CategoryControllerTest.java, backend/src/test/java/com/staccato/category/controller/CategoryControllerV2Test.java, backend/src/test/java/com/staccato/category/controller/CategoryControllerV3Test.java, backend/src/test/java/com/staccato/category/domain/CategoryTest.java, backend/src/test/java/com/staccato/category/service/CategoryServiceTest.java, backend/src/test/java/com/staccato/fixture/category/CategoryFixtures.java, backend/src/test/java/com/staccato/staccato/repository/StaccatoRepositoryTest.java
- #821
- 각 카테고리 응답에 함께하는 사람 목록 & 총 스타카토 개수 응답을  포함
- 함께하는 사람 목록에는 모든 사용자를 포함합니다. 몇 명을 표기할지는 디자인에 따라 클라이언트 측에서 구현합니다.
- 총 스타카토 개수를 매번 조회하는 것(count 쿼리) 성능 부하가 크다고 하지만, 실행 계획을 살펴보았을 때 커버링 인덱스를 사용하기 때문에 `과연 성능 부하가 그렇게 클까?`하는 생각이 들었어요. 직접 확인해보고 싶은 욕심이 있어서 관련 내용은 이 pr에 추가해놓도록 하겠습니다.
- 전체 회의에서는 우선은 count 쿼리를 사용하는 방식으로 배포 후 추가 작업을 하는 것을 말씀드렸기에 우선 pr을 올렸습니다. 성능 테스트 및 반정규화 방식을 적용하는 것은 이번 스프린트 내에 진행하도록 해볼게요!
현재 카테고리에 속한 스타카토 개수는 **count 쿼리 방식**으로 구현했습니다.
커버링 인덱스를 활용하고 있기 때문에, 일반적인 count(*)에 비해 성능 부하는 크지 않을 것으로 '추측'했습니다.
다만 InnoDB는 MVCC 기반 스토리지 엔진이기 때문에, 커버링 인덱스를 타더라도 각 row에 대해 visibility check가 발생하며, 결과적으로 row 수가 많아질수록 성능은 선형 증가할 수 있습니다.
그럼에도 불구하고 일차적으로 count 쿼리를 선택한 이유는 다음과 같습니다:
- 현재 데이터 규모가 작아 성능 부하가 크지 않다
- 반정규화를 도입할 경우 정합성 유지를 위한 동시성 관리 전략이 필요하다
- 이에 따라 복잡도보다 단순성과 안정성을 우선시했다
물론 반정규화도 좋은 방안입니다. …
=> feat: 카테고리 목록 조회 API V3 구현 #821

backend/src/main/java/com/staccato/category/service/dto/response/CategoryResponseV3.java, backend/src/test/java/com/staccato/category/controller/CategoryControllerV3Test.java
- #
- 카테고리 목록 조회 V3 API에서 각 카테고리의 공동 카테고리 여부(isShared)를 누락하여 추가했습니다.
=> fix: 누락된 isShared 필드 추가

backend/src/main/java/com/staccato/category/domain/Category.java, backend/src/main/java/com/staccato/category/service/CategoryService.java, backend/src/main/java/com/staccato/category/service/dto/response/CategoryDetailResponseV3.java, backend/src/main/java/com/staccato/category/service/dto/response/CategoryResponseV3.java, backend/src/main/java/com/staccato/config/swagger/SwaggerExamples.java, backend/src/test/java/com/staccato/category/controller/CategoryControllerTest.java, backend/src/test/java/com/staccato/category/controller/CategoryControllerV2Test.java, backend/src/test/java/com/staccato/category/controller/CategoryControllerV3Test.java, backend/src/test/java/com/staccato/category/domain/CategoryTest.java, backend/src/test/java/com/staccato/category/service/CategoryServiceTest.java
- #836 
- 특정 카테고리 조회 시 요청한 사용자의 역할(`myRole`)을 응답 필드로 함께 반환합니다.
- 카테고리 목록 조회 시 모든 함께하는 사람 목록을 반환하지 않고, 최대 3명의 목록과 함께 총 함께하는 사람 수를 응답 필드로 추가하여 반환합니다.
- 일부 사용자만 반환하는 것은 뷰의 요구사항일 뿐더러, 이를 위해 쿼리를 분리 (limit 3 조회 + count 조회)하는 것은 오히려 DB 부하를 증가시키는 방향이라고 생각했습니다. 따라서, 기존대로 fetch join으로 모든 categoryMember를 가져오되, dto에서 `size()`와 stream 연산에서 `limit(n)`을 사용하여 요구사항에 맞는 응답을 구성하도록 구현했습니다.
=> refactor: 카테고리 API 응답 수정 #836

backend/src/main/java/com/staccato/config/swagger/SwaggerExamples.java, backend/src/main/java/com/staccato/invitation/service/dto/response/CategoryInvitationRequestedResponse.java, backend/src/test/java/com/staccato/invitation/controller/InvitationControllerTest.java
- #
- 보낸 초대 취소 시 식별자가 필요하므로 보낸 초대 목록 조회 응답 필드로 invitationId 추가
=> feat: 보낸 초대 목록 조회 시 식별자 응답 필드 포함하도록 추가

android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/bindingadapter/TextBindingAdapter.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatoupdate/viewmodel/StaccatoUpdateViewModel.kt, android/Staccato_AN/app/src/main/res/values/strings.xml
- #857 
1. `스타카토` 조회 요청, `카테고리 후보` 조회 요청이 각 코루틴에서 병렬로 실행됨. (각 요청의 완료 순서 보장 X)
2. 이 때 조회된 `스타카토`의 `visitedAt`을 기준으로, 조회된 `카테고리 후보`들 중 선택 가능한 카테고리를 필터링
3. 필터링 결과를 `selectableCategories` LiveData에 저장
아직 `카테고리 후보`가 불러와지지 않은 상태에서 아래 코드(2번의 필터링에 해당)를 수행하면 `selectableCategories`에 null이 들어감.
따라서 카테고리 선택란을 터치했을 때 `NullPointerException`이 발생하던 것!
```kotlin
_selectableCategories.value = categoryCandidates.value?.filterBy(staccato.visitedAt.toLocalDate())
```
모두 불러와진 뒤 카테고리 선택하도록 순서 보장
```kotlin
fun fetchTargetData(staccatoId: Long) {
viewModelScope.launch { // 최상위 코루틴
val staccatoJob = launch { fetchStaccatoBy(staccatoId) } // 자식 코루틴 1 - 스타카토 조회 요청
val categoryCandidatesJob = launch { fetchCategoryCandidates() } // 자식 코루틴 2 - 카테고리 후보 조회 요청
staccatoJob.join()
categoryCandidatesJob.join() …
```
=> fix: 스타카토 수정 화면 카테고리 클릭 시 앱이 터지는 버그2 #857

backend/src/main/java/com/staccato/auth/controller/AuthControllerV2.java, backend/src/main/java/com/staccato/auth/controller/docs/AuthControllerV2Docs.java, backend/src/main/java/com/staccato/auth/service/AuthService.java, backend/src/main/java/com/staccato/auth/service/dto/response/LoginResponseV2.java, backend/src/test/java/com/staccato/auth/controller/AuthControllerV2Test.java, backend/src/test/java/com/staccato/auth/service/AuthServiceTest.java
- 복구 코드로 사용자 조회 API와 로그인 API에 memberId 응답 필드를 추가합니다.
- 응답 필드에 변경 사항이 생겼으므로 V2 버저닝을 했습니다.
=> feat: 로그인, 복구 코드 조회 시 응답 필드로 사용자 식별자 추가한 V2 구현

backend/src/main/java/com/staccato/member/service/MemberService.java, backend/src/main/java/com/staccato/member/service/dto/request/MemberReadRequest.java, backend/src/test/java/com/staccato/member/controller/MemberControllerTest.java, backend/src/test/java/com/staccato/member/service/MemberServiceTest.java
- 컨트롤러 단위 테스트에서, 필수값이 아닌 Long 타입 요청 인자가 null로 전달되면 기본형 long으로는 바인딩이 되지 않음을 확인했습니다.
- 해당 API 구현 당시, 내부 DTO에서는 long 기본형을 사용하고 있었고, 이를 일관되게 유지하는 쪽으로 논의되었었습니다.
하지만 이번 PR에서는 다음과 같은 이유로 컨트롤러 요청 파라미터에는 래퍼 타입인 Long을 사용하는 방향으로 수정했습니다.
- 필수값이 아님을 명확하게 표현하기 위한 선택입니다!
- long은 기본형이라 null을 받을 수 없고, 값이 없을 경우 자동으로 0으로 바인딩됩니다..
- 그러나 0이라는 값은 실질적인 의미를 가질 수 있기 때문에, "값이 없는 상태"와 "0이라는 값이 전달된 상태"를 구분하는 데 모호함이 있다고 생각해요.
- 따라서, Long은 null을 받을 수 있기 때문에, 해당 파라미터가 아예 전달되지 않았다는 사실을 명확하게 표현할 수 있다고 생각해요.
이러한 이유로, DTO에서의 타입 일관성(wrapper가 아닌 원시 타입을 사용)보다, API 표현의 명확성이 중요하다고 생각해서 Long 타입을 사용하는 방향으로 수정했습니다!
=> fix: 필수값이 아닌 Long이 원시값으로 파싱 안되는 오류 수정

backend/src/main/java/com/staccato/invitation/repository/CategoryInvitationRepository.java, backend/src/main/java/com/staccato/notification/controller/NotificationController.java, backend/src/main/java/com/staccato/notification/controller/docs/NotificationControllerDocs.java, backend/src/main/java/com/staccato/notification/service/NotificationService.java, backend/src/main/java/com/staccato/notification/service/dto/response/NotificationExistResponse.java, backend/src/test/java/com/staccato/ControllerTest.java, backend/src/test/java/com/staccato/notification/controller/NotificationControllerTest.java, backend/src/test/java/com/staccato/notification/service/NotificationServiceTest.java
- #877 
- 홈 화면 진입 시 알림 존재 여부를 확인할 수 있는 API를 `/notifications/exists` 경로로 구현했습니다.
- 현재는 받은 초대 목록 기준으로 알림의 존재 여부를 판단하지만, 이는 구현 방식(HOW)에 해당하며 클라이언트가 궁금한 것은 "알림이 존재하는가?"라는 목적(WHAT)이기 때문에 URI에는 포함하지 않았습니다.
- 현재 알림 종류는 받은 초대만 존재하지만, 앞으로 버전 업데이트 알림, 참여 알림 등 다양한 종류가 추가될 수 있으므로, **알림이라는 추상 개념을 기준으로 한 Notification 도메인**을 분리해 관리합니다.
- 알림 기능에 문제가 생겼을 때 다른 도메인에 영향을 주지 않아야 하며, 이는 알림이 하나의 독립된 문제 영역임을 의미합니다. 
- 도메인은 반드시 영속화되는 엔티티일 필요는 없으며, 우리가 해결하고자 하는 문제의 중심 단위라는 점에서 Notification은 하나의 독립된 도메인이라고 생각해요.
- FCM이 도입되면 알림 존재 여부 판단 로직은 현재처럼 DB 기반이 아닌 푸시 메시지 기반 등으로 변경될 수 있습니다. 따라서 지금의 `초대 목록 기준 존재 여부 확인`은 내부 구현에 해당하며 외부에는 노출하지 않는 것이 적절하다고 생각했어요!
- 향후 알림 종류별로 개별 API가 필요해질 경우, 그때 명확하게 분리된 엔드포인트(`/notifications/invitations/exists` 등)를 제공하고자 합니다. 현재는 임시적으로 홈화면에서의 알림 존재여부 조회 & 마이 페이지 내 카테고리 초대 관리에 대한 알림 존재 여부 조회 모두 …
=> feat: 알림 존재 여부 조회 API 구현 #877

android/Staccato_AN/app/src/main/java/com/on/staccato/data/network/ApiResultCall.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/data/network/ApiResultCallAdapter.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/data/network/ApiResultCallAdapterFactory.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/data/network/ErrorConverter.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/data/network/ResponseHandler.kt, android/Staccato_AN/app/src/main/java/com/on/staccato/di/module/NetworkModule.kt, android/Staccato_AN/app/src/test/java/com/on/staccato/data/ApiResultCallAdapterTest.kt, android/Staccato_AN/app/src/test/java/com/on/staccato/data/MockWebServerProvider.kt
- #881 
<br>
https://github.com/user-attachments/assets/133e0635-c2a4-4a19-bedc-a828a1c37058
<br>
- ErrorResponse 생성 방식 변경
- NetworkModule 순환 참조 문제 해결
- ApiResultCallAdapterTest 수정
<br>
<br>
정상 동작 여부를 ApiResultCallAdapterTest로 테스트 완료했습니다.
<br>
=> fix: ErrorResponse 변환 오류 및 NetworkModule 순환 참조 문제 해결 #881

.github/workflows/android-cd.yml, .github/workflows/android-ci-cd-dev.yml
- #890 
<br>
Release 빌드 과정에서 앱 서명이 적용되지 않아 업로드가 거부된 문제를 해결했습니다.
- 앱 서명 파일의 변경된 경로가 CD 워크플로에 반영되지 않아, Gradle이 서명 키, 암호 등을 찾지 못해 서명을 할 수 없었습니다.
- **파일 경로를 수정하여 앱 서명이 정상적으로 진행되도록 했습니다.**
- 워크플로에서 빌드에 필요한 파일을 생성하는 명령어를 정리했습니다.
<br>
단지 혼자만의 고민입니다...! 아직 조금 더 알아보아야 할 것 같습니다.
- 앱 서명을 하는 동작이 Gradle 파일에 있어도 괜찮을까요?
- Gradle은 작성한 코드(프로젝트)가 실행될 수 있도록 실행 파일을 빌드해주고, 이에 필요한 데이터를 관리하는 역할을 한다고 생각합니다.
- **배포를 위해 앱 서명**을 하는 것은 **단순히 프로젝트를 실행할 수 있도록 빌드하는 것**과는 조금 다른 책임이라고 생각이 들었어요.
- 그래서 서명을 하는 작업을 gradle이 아니라 프로젝트 외부(Github Action)에서 수행시키는 것을 고민하고 있습니다.
<br>
- main 브랜치에 먼저 적용되어야 이후 배포에 Release 워크플로가 실행되어 자동 배포가 이루어질 수 있습니다!
- 빠른 확인과 승인 부탁드립니다!
<br>
=> fix: 안드로이드 CD 워크플로에서 앱 서명이 적용되지 않는 문제 해결 #890

android/Staccato_AN/app/src/main/java/com/on/staccato/data/network/ResponseHandler.kt
- #895 
<br>
- 10MB를 초과하는 이미지에 대한 업로드 오류 처리가 누락되어, 해당 로직을 추가했습니다.
<br>
<br>
=> fix: 누락된 이미지 업로드 시 용량 초과 오류 처리 추가 #895

backend/src/main/java/com/staccato/staccato/service/dto/response/StaccatoLocationResponseV2.java, backend/src/test/java/com/staccato/auth/controller/AuthControllerTest.java, backend/src/test/java/com/staccato/auth/controller/AuthControllerV2Test.java, backend/src/test/java/com/staccato/category/controller/CategoryControllerTest.java, backend/src/test/java/com/staccato/category/controller/CategoryControllerV2Test.java, backend/src/test/java/com/staccato/category/controller/CategoryControllerV3Test.java, backend/src/test/java/com/staccato/comment/controller/CommentControllerTest.java, backend/src/test/java/com/staccato/invitation/controller/InvitationControllerTest.java, backend/src/test/java/com/staccato/member/controller/MemberControllerTest.java, backend/src/test/java/com/staccato/member/controller/MyPageControllerTest.java, backend/src/test/java/com/staccato/member/controller/MyPageControllerV2Test.java, backend/src/test/java/com/staccato/notification/controller/NotificationControllerTest.java, backend/src/test/java/com/staccato/staccato/controller/StaccatoControllerTest.java, backend/src/test/java/com/staccato/staccato/controller/StaccatoControllerV2Test.java
- #912
- 전체 스타카토 목록 조회 API V2에 제목, 날짜 응답 필드를 추가
- 컨트롤러 단위 테스트에서 응답 형식 관련 테스트를 다음과 같이 작성해왔습니다.
```
mockMvc.perform(get("/v3/categories/{categoryId}", categoryId)
.header(HttpHeaders.AUTHORIZATION, "token"))
.andExpect(status().isOk())
.andExpect(content().json(expectedResponse));
```
- `MockMvcResultMatcher.content.json` 기본 설정은 `LENIENT` 모드로, 존재하는 필드에 대해서만 일치 여부를 검증합니다. 
- 즉, 누락된 필드 존재함에도 테스트 통과합니다. 
- 이는 테스트 목적에 맞지 않으므로, STRICT 모드로 설정하여 모든 필드가 일치해야만 테스트가 통과하도록 강제했습니다.
마지막 커밋은 테스트 STRICT 모드 변경 관련 커밋입니다! 전체 파일 변경으로 리뷰 시 참고해주세요:>
=> feat: 지도 기준 스타카토 목록 조회 API 응답 필드 추가 #912

backend/src/main/java/com/staccato/category/domain/Category.java, backend/src/test/java/com/staccato/category/domain/CategoryTest.java
- #928 
- 공동카테고리에 함께하는 사람이 추가되면, 해당 카테고리의 updatedAt 갱신
- 함께하는 사람이 삭제되는 경우는 갱신하지 않습니다.
=> feat: 공동카테고리에 함께하는 사람이 추가되면, 카테고리의 updatedAt 갱신 #928

backend/src/main/java/com/staccato/notification/service/FcmService.java, backend/src/main/java/com/staccato/notification/service/dto/message/AcceptInvitationMessage.java, backend/src/main/java/com/staccato/notification/service/dto/message/CommentCreatedMessage.java, backend/src/main/java/com/staccato/notification/service/dto/message/MessageType.java, backend/src/main/java/com/staccato/notification/service/dto/message/PushMessage.java, backend/src/main/java/com/staccato/notification/service/dto/message/ReceiveInvitationMessage.java, backend/src/main/java/com/staccato/notification/service/dto/message/StaccatoCreatedMessage.java, backend/src/test/java/com/staccato/notification/service/FcmServiceTest.java
- #938
- Notification과 Data 모두 담도록 FcmService 변경
- toNotification()과 toData()로 캡슐화
=> feat: 알림 구성 변경 (Notification & Data 모두 전달) #938

backend/src/main/java/com/staccato/category/controller/CategoryController.java, backend/src/main/java/com/staccato/category/controller/CategoryControllerV2.java, backend/src/main/java/com/staccato/category/controller/CategoryControllerV3.java, backend/src/main/java/com/staccato/category/controller/CategoryControllerV4.java, backend/src/main/java/com/staccato/category/controller/docs/CategoryControllerDocs.java, backend/src/main/java/com/staccato/category/controller/docs/CategoryControllerV2Docs.java, backend/src/main/java/com/staccato/category/controller/docs/CategoryControllerV3Docs.java, backend/src/main/java/com/staccato/category/controller/docs/CategoryControllerV4Docs.java, backend/src/main/java/com/staccato/category/service/CategoryService.java, backend/src/main/java/com/staccato/category/service/StaccatoCursor.java, backend/src/main/java/com/staccato/category/service/dto/request/CategoryStaccatoPaginationRequest.java, backend/src/main/java/com/staccato/category/service/dto/response/CategoryDetailResponseV4.java, backend/src/main/java/com/staccato/category/service/dto/response/CategoryStaccatoLocationResponses.java, backend/src/main/java/com/staccato/category/service/dto/response/CategoryStaccatoResponses.java, backend/src/main/java/com/staccato/config/OpenApiConfig.java, backend/src/main/java/com/staccato/config/swagger/SwaggerExamples.java, backend/src/main/java/com/staccato/staccato/controller/docs/StaccatoControllerV2Docs.java, backend/src/main/java/com/staccato/staccato/repository/StaccatoRepository.java, backend/src/test/java/com/staccato/category/controller/CategoryControllerTest.java, backend/src/test/java/com/staccato/category/controller/CategoryControllerV2Test.java, backend/src/test/java/com/staccato/category/controller/CategoryControllerV3Test.java, backend/src/test/java/com/staccato/category/service/CategoryServiceTest.java, backend/src/test/java/com/staccato/category/service/StaccatoCursorTest.java, backend/src/test/java/com/staccato/staccato/repository/StaccatoRepositoryTest.java
- #966 
- 카테고리 내 스타카토 목록 조회 시 커서 기반 페이지네이션을 합니다.
- 주어진 커서가 없다면 첫 페이지를 조회합니다.
- 응답으로 마지막 요소로 nextCursor를 제공합니다.
- 조회 시 주어진 Cursor 다음 값부터 조회합니다.
- 카테고리 내 스타카토 목록 조회가 `/categories` 내부에서 함께 이루어졌는데, 성능 개선 목적으로 API를 분리합니다. 자세한 내용은 이슈를 참고해주세요.
- createdAt으로 인해 테스트 반복성이 보장되고 있지 않습니다...
- 슬랙으로 제안했던 아이디어를 적용해보며 createdAt에 의존한 테스트 신뢰도 개선이 필요할 듯 합니다.
- 커서 필드에서 **createdAt을 사용하지 않기로 결정했습니다**
- `createdAt`과 id는 항상 동일한 생성 순서를 갖는 필드입니다.
- `createdAt`은 데이터 생성 시점에 `LocalDateTime.now()`로 기록되며, id는 AUTO_INCREMENT로 할당되기 때문에, 두 값은 사실상 동일한 정렬 순서를 보장합니다.
- 따라서 정렬 및 커서 기준으로 id 하나만으로 충분하다고 판단했습니다. 또한 id는 단조 증가하는 정수값이므로 커서로 사용하기에 더 간결하고 비교도 빠릅니다.
- 즉, visitedAt DESC, id DESC로도 기존의 visitedAt DESC, createdAt DESC, id DESC와 동일한 정렬 순서를 재현할 수 있습니다.
- **물론, DB의 식별자 생성 전략에 의존적이라는 우려 사항도 있습니다.**
- 하지만, DB 식별자 생성 전략이 변경될 …
=> feat: 카테고리 내 스타카토 목록 조회 시 페이지네이션 및 API 분리 #966
