- .github/workflows/backend-ci.yml
> build: develop-be 브랜치의 CI 설정

- backend/src/main/java/com/staccato/exception/ExceptionResponse.java
- backend/src/main/java/com/staccato/exception/GlobalExceptionHandler.java
close #29 
- `GlobalExceptionHandler` 구현
- `ExceptionResponse Dto` 생성
`ExceptionHandler`와 `ExceptionResponse`의 패키지 구조 한번 확인해주세요!
> feat: ControllerAdvice 생성 #29

- backend/src/main/java/com/staccato/visit/controller/VisitController.java
- backend/src/main/java/com/staccato/visit/domain/Visit.java
- backend/src/main/java/com/staccato/visit/domain/VisitImage.java
- backend/src/main/java/com/staccato/visit/domain/VisitLog.java
- backend/src/main/java/com/staccato/visit/repository/VisitRepository.java
- backend/src/main/java/com/staccato/visit/service/VisitService.java
- close #31 
-  visit domain skeleton 코드 작성했습니다.
> feat: Visit domain skeleton 코드 작성 #31

- backend/src/main/java/com/staccato/exception/GlobalExceptionHandler.java
- backend/src/main/java/com/staccato/travel/controller/TravelController.java
- backend/src/main/java/com/staccato/travel/domain/Mate.java
- backend/src/main/java/com/staccato/travel/domain/Travel.java
- backend/src/main/java/com/staccato/travel/repository/TravelRepository.java
- backend/src/main/java/com/staccato/travel/service/TravelService.java
- backend/src/main/java/com/staccato/travel/service/dto/request/TravelRequest.java
- backend/src/main/java/com/staccato/travel/service/dto/response/TravelResponse.java
- #32 
- `Travel Controller` 작성
- `Travel Service` 작성
- `Travel Repository` 작성
- `Travel DTO` 작성
- `Trvael Domain` 빌더 패턴 적용
- 날짜 형식 예외 핸들링
> feat: Travel Domain Skeleton Code 작성 #32

- backend/.gitignore
- backend/Dockerfile
- backend/build.gradle
- backend/docker-compose.yml
- backend/src/main/resources/application.yml
- #27 
- `local`에 `DB container`와 `Spring Application container` 설정
- 배포서버에 `Docker` 띄우기
> build: Docker Compose Setting #27

- .github/workflows/android-ci.yml
> build: develop-an 브랜치의 CI 파일 문법 오류 수정 #45

- .github/workflows/android-ci.yml
- #47 
- local.properties 생성 시점 수정
> fix: develop-an의 CI yml 파일 문법 오류 수정 #47

- .github/workflows/backend-ci-cd-dev.yml
- backend/src/main/java/com/staccato/member/domain/Member.java
- backend/src/main/java/com/staccato/travel/domain/Travel.java
- backend/src/main/java/com/staccato/travel/domain/TravelMember.java
- backend/src/main/java/com/staccato/travel/repository/MateRepository.java
- backend/src/main/java/com/staccato/travel/repository/TravelMemberRepostiory.java
- backend/src/main/java/com/staccato/travel/service/TravelService.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/staccato/travel/service/TravelServiceTest.java
> refactor: 중간 테이블 엔티티 수정 #56

- backend/src/main/java/com/staccato/visit/controller/VisitController.java
- backend/src/main/java/com/staccato/visit/repository/VisitImageRepository.java
- backend/src/main/java/com/staccato/visit/repository/VisitLogRepository.java
- backend/src/main/java/com/staccato/visit/repository/VisitRepository.java
- backend/src/main/java/com/staccato/visit/service/VisitService.java
- backend/src/main/java/com/staccato/visit/service/dto/response/VisitDetailResponse.java
- backend/src/main/java/com/staccato/visit/service/dto/response/VisitLogResponse.java
- backend/src/main/java/com/staccato/visit/service/dto/response/VisitResponses.java
- backend/src/test/java/com/staccato/visit/controller/VisitIntegrationTest.java
- backend/src/test/java/com/staccato/visit/repository/VisitImageRepositoryTest.java
- backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
> feat: 특정 방문 기록 조회 API 구현 #25

- backend/src/main/java/com/staccato/pin/domain/Pin.java
- backend/src/test/java/com/staccato/travel/domain/TravelTest.java
- backend/src/test/java/com/staccato/travel/service/TravelServiceTest.java
- backend/src/test/java/com/staccato/visit/controller/VisitIntegrationTest.java
- backend/src/test/java/com/staccato/visit/repository/VisitImageRepositoryTest.java
- backend/src/test/java/com/staccato/visit/repository/VisitLogRepositoryTest.java
- backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
> feat: Pin 연관관계 추가 #80

- backend/src/main/java/com/staccato/exception/GlobalExceptionHandler.java
> feat: logging 추가 #86

- backend/src/main/java/com/staccato/travel/service/TravelService.java
- backend/src/main/java/com/staccato/travel/service/dto/response/TravelDetailResponse.java
- backend/src/main/java/com/staccato/travel/service/dto/response/VisitResponse.java
- backend/src/main/java/com/staccato/visit/service/VisitService.java
- backend/src/main/java/com/staccato/visit/service/dto/request/VisitRequest.java
- backend/src/main/java/com/staccato/visit/service/dto/response/VisitDetailResponse.java
- backend/src/main/java/com/staccato/visit/service/dto/response/VisitLogResponse.java
- backend/src/test/java/com/staccato/visit/controller/VisitIntegrationTest.java
- backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
> fix: 명세서와 다른 응답 필드 수정 #94

- backend/src/main/java/com/staccato/travel/repository/TravelMemberRepository.java
- backend/src/main/java/com/staccato/travel/service/TravelService.java
- backend/src/test/java/com/staccato/travel/controller/TravelIntegrationTest.java
- backend/src/test/java/com/staccato/travel/repository/TravelMemberRepositoryTest.java
- backend/src/test/java/com/staccato/travel/service/TravelServiceTest.java
> feat: 여행 상세 목록 조회 시 최신순 정렬 #96

- backend/src/main/java/com/staccato/travel/service/TravelService.java
- backend/src/main/java/com/staccato/visit/repository/VisitRepository.java
- backend/src/test/java/com/staccato/travel/service/TravelServiceTest.java
> feat: 특정 여행 상세 조회 API에서 방문 기록 오래된 순 정렬 #101

- backend/build.gradle
- backend/src/main/java/com/staccato/config/OpenApiConfig.java
- backend/src/main/java/com/staccato/exception/GlobalExceptionHandler.java
- backend/src/main/java/com/staccato/travel/controller/TravelController.java
- backend/src/main/java/com/staccato/travel/controller/docs/TravelControllerDocs.java
- backend/src/main/java/com/staccato/travel/service/dto/request/TravelRequest.java
- backend/src/main/resources/application.yml
> docs: swagger 컨벤션 설정 및 적용

- .github/workflows/backend-ci-cd-dev.yml
- #84 
- CD 작업 시 사용하지 않는 도커 이미지 삭제
> build: 사용하지 않는 도커 이미지 삭제 workflow 구성 #84

- backend/src/main/java/com/staccato/config/domain/BaseEntity.java
- backend/src/main/java/com/staccato/visit/domain/VisitLog.java
- backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
- #125 
- visit log에 base entity 추가 및 논리적 삭제 구현
- base Entity 필드명 수정
> refactor: 엔티티 수정 #125

- .github/workflows/android-ci-apk.yml
- .github/workflows/android-ci.yml
> build: develop-an의 CI 테스트 자동화 추가 및 데모 APK 추출 #78

- android/Staccato_AN/.gitignore
- android/Staccato_AN/app/build.gradle.kts
- android/Staccato_AN/build.gradle.kts
- android/Staccato_AN/gradle/libs.versions.toml
- #136
- Firebase Analytics 의존성 추가
- Crashlytics 의존성 추가
- gitignore google-service.json 추가
- 로깅 전략 수립 후 이벤트 로깅 코드 작성
> build: Firebase Analytics, Crashlytics 설정 #136

- .github/workflows/backend-ci-cd-dev.yml
- backend/src/main/java/com/staccato/auth/controller/AuthControllerDocs.java
- backend/src/main/java/com/staccato/travel/controller/TravelController.java
- backend/src/main/java/com/staccato/travel/controller/docs/TravelControllerDocs.java
- backend/src/main/java/com/staccato/travel/domain/Travel.java
- backend/src/main/java/com/staccato/travel/service/TravelService.java
- backend/src/main/java/com/staccato/travel/service/dto/response/TravelIdResponse.java
- backend/src/test/java/com/staccato/auth/controller/AuthControllerTest.java
- backend/src/test/java/com/staccato/travel/controller/TravelControllerTest.java
- backend/src/test/java/com/staccato/travel/controller/TravelIntegrationTest.java
- backend/src/test/java/com/staccato/travel/service/TravelServiceTest.java
- #141
- S3는 아직 구현이 안되었으므로 우선 body로 받을 수 있도록 구현 및 명세서에 반영
> feat: 여행 상세 생성 API 수정 #141

- backend/src/main/java/com/staccato/member/domain/Nickname.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/staccato/member/domain/NicknameTest.java
> fix: 닉네임 형식 수정 #157

- .github/workflows/android-ci-apk.yml
- .github/workflows/android-ci.yml
- #115 
- 추후 개발 중에 `local.properties`와 같은 **로컬 파일에 데이터(API 키 등)를 추가**해야 하거나,  
이번 `google-services.json` 과 같이 **Git 버전 관리에 해당하지 않는 설정 파일을 추가**하여야 하는 경우 저에게 알려주세요!
- 배포 자동화 추가 : Release Apk(AAB) 추출하여 Firebase 또는 GooglePlay에 업로드
> build: `develop-an`의 android-ci 수정 #115

- .github/workflows/android-ci-apk.yml
- .github/workflows/android-ci.yml
- #115 
- 환경 변수(`BASE_URL`과 `GOOGLE_SERVICES_JSON`)를 설정하는 위치를 변경하였습니다.
> fix: android-ci 환경변수 생성 위치 조정

- .github/pull_request_template.md
- 오타 수정 및 개행 조정
- Issue Number 태그 형식 추가
> docs: PR 템플릿 오타 수정

- .github/workflows/backend-ci-cd-dev.yml
- backend/src/main/java/com/staccato/StaccatoApplication.java
> feat: swagger https 적용하기 #184

- backend/src/main/java/com/staccato/config/OpenApiConfig.java
- backend/src/main/resources/error-appender.xml
- backend/src/main/resources/info-appender.xml
- backend/src/main/resources/warn-appender.xml
- #188 
- `Swagger` 인증 헤더 형식 변경
- `Logging` 정보 수정
> fix: Swagger 인증 헤더 형식 변경 #188

- .github/workflows/backend-ci-cd-stage.yml
> fix: image push 시 권한 오류 수정

- backend/src/main/java/com/staccato/auth/service/AuthService.java
- backend/src/main/java/com/staccato/config/auth/AdminProperties.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-stage.yml
- #199
- admin용 닉네임에 대해 admin용 정보 불러올 수 있도록 구현
> feat: admin용 계정 로직 추가 #199

- backend/src/main/resources/logback-spring.xml
> fix: add stage logging

- backend/src/main/java/com/staccato/StaccatoApplication.java
- backend/src/main/java/com/staccato/config/OpenApiConfig.java
- #207 
- swagger가 stage, dev, local 환경에서 모두 수행되도록 url 설정
> refactor: swagger url 재설정 (dev/stage/local) #207

- backend/src/main/java/com/staccato/memory/controller/docs/MemoryControllerDocs.java
- backend/src/main/java/com/staccato/memory/service/dto/response/MemoryDetailResponse.java
> feat: 추억 조회 API 수정 #227

- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/ImageApiService.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/StaccatoClient.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/dto/image/ImageResponse.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/image/ImageApiService.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/image/ImageDefaultRepository.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/domain/repository/ImageRepository.kt
- #239 
- Dto
- ApiService
- Repository
> feat: s3 api 연결 #239

- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/dto/mapper/TimelineMapper.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/dto/timeline/TimelineMemoryDto.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/memory/MemoryApiService.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/memory/MemoryDataSource.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/memory/MemoryDefaultRepository.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/memory/MemoryRemoteDataSource.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/domain/repository/MemoryRepository.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/memoryupdate/viewmodel/MemoryUpdateViewModel.kt
- #246 
<br>
- 추억 수정 후 홈으로 이동하는 버그
- 추억 타임라인 조회 버그
<br>
- 추억 기능 리팩터링
> fix: 추억 기능 버그 수정 #246

- .github/workflows/backend-ci-cd-dev.yml
- backend/src/main/java/com/staccato/config/auth/TokenProvider.java
- backend/src/main/java/com/staccato/memory/controller/MemoryController.java
- backend/src/main/java/com/staccato/memory/controller/docs/MemoryControllerDocs.java
- backend/src/main/java/com/staccato/memory/domain/Memory.java
- backend/src/main/java/com/staccato/memory/service/MemoryService.java
- backend/src/main/java/com/staccato/memory/service/dto/response/MemoryDetailResponse.java
- backend/src/main/java/com/staccato/memory/service/dto/response/MemoryIdResponse.java
- backend/src/main/java/com/staccato/memory/service/dto/response/MomentResponse.java
- backend/src/test/java/com/staccato/auth/service/AuthServiceTest.java
- backend/src/test/java/com/staccato/config/auth/TokenProviderTest.java
- backend/src/test/java/com/staccato/memory/controller/MemoryControllerTest.java
- backend/src/test/java/com/staccato/memory/service/MemoryServiceTest.java
- #261 
- 이미지 컨트롤러 분리로 변경된 사항 반영
- 인증 관련 테스트 추가
> feat: 추억 수정 API 수정 #261

- backend/src/main/java/com/staccato/moment/controller/docs/MomentControllerDocs.java
- backend/src/test/java/com/staccato/moment/service/MomentServiceTest.java
> feat: 순간 삭제 API 구현 #243

- backend/src/main/java/com/staccato/exception/GlobalExceptionHandler.java
- backend/src/main/java/com/staccato/image/controller/docs/ImageControllerDocs.java
- backend/src/main/java/com/staccato/image/service/ImageService.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-stage.yml
> refactor: S3 로직 리팩터링 #274

- backend/src/main/java/com/staccato/auth/service/dto/request/LoginRequest.java
- backend/src/main/java/com/staccato/member/domain/Nickname.java
- backend/src/test/java/com/staccato/member/domain/NicknameTest.java
> fix: 닉네임 앞뒤 공백 제거 #277

- backend/src/main/java/com/staccato/moment/domain/Feeling.java
- backend/src/main/java/com/staccato/moment/service/dto/response/MomentDetailResponse.java
- backend/src/main/java/com/staccato/moment/service/dto/response/MomentLocationResponses.java
- backend/src/test/java/com/staccato/fixture/moment/MomentDetailResponseFixture.java
> fix: 순간 조회 응답 형식 수정

- backend/src/main/java/com/staccato/memory/service/dto/response/MomentResponse.java
- backend/src/main/java/com/staccato/moment/domain/Moment.java
- backend/src/main/java/com/staccato/moment/service/dto/response/MomentDetailResponse.java
- backend/src/test/java/com/staccato/fixture/moment/MomentDetailResponseFixture.java
- backend/src/test/java/com/staccato/moment/controller/MomentControllerTest.java
- backend/src/test/java/com/staccato/moment/service/MomentServiceTest.java
- #283 
- 순간 날짜 반환 형식 변경(`LocalDate` -> `LocalDateTime`)
> fix: 순간 날짜 반환 형식 변경 #283

- backend/src/main/java/com/staccato/exception/GlobalExceptionHandler.java
- backend/src/main/java/com/staccato/memory/controller/MemoryController.java
- backend/src/main/java/com/staccato/memory/controller/docs/MemoryControllerDocs.java
- backend/src/main/java/com/staccato/memory/repository/MemoryMemberRepository.java
- backend/src/main/java/com/staccato/memory/service/MemoryService.java
- backend/src/main/java/com/staccato/memory/service/dto/response/MemoryNameResponse.java
- backend/src/main/java/com/staccato/memory/service/dto/response/MemoryNameResponses.java
- backend/src/test/java/com/staccato/comment/controller/CommentControllerTest.java
- backend/src/test/java/com/staccato/comment/service/CommentServiceTest.java
- backend/src/test/java/com/staccato/fixture/memory/MemoryNameResponsesFixture.java
- backend/src/test/java/com/staccato/fixture/moment/CommentFixture.java
- backend/src/test/java/com/staccato/fixture/moment/MomentFixture.java
- backend/src/test/java/com/staccato/image/infrastructure/FakeS3ObjectClient.java
- backend/src/test/java/com/staccato/memory/controller/MemoryControllerTest.java
- backend/src/test/java/com/staccato/memory/repository/MemoryMemberRepositoryTest.java
- backend/src/test/java/com/staccato/memory/service/MemoryServiceTest.java
- #281
- 현재 날짜를 포함하고 있는 추억 목록 조회 구현
> feat: 현재 날짜를 포함하고 있는 추억 목록 조회 구현 #281

- backend/src/main/java/com/staccato/moment/controller/MomentController.java
- backend/src/main/java/com/staccato/moment/domain/MomentImage.java
- backend/src/main/java/com/staccato/moment/domain/MomentImages.java
- backend/src/test/java/com/staccato/moment/service/MomentServiceTest.java
> refactor: 순간 수정 이미지 순서 적용 #287

- backend/src/main/java/com/staccato/moment/service/dto/response/MomentDetailResponse.java
- backend/src/test/java/com/staccato/comment/controller/CommentControllerTest.java
- backend/src/test/java/com/staccato/fixture/moment/MomentDetailResponseFixture.java
- backend/src/test/java/com/staccato/memory/controller/MemoryControllerTest.java
- backend/src/test/java/com/staccato/moment/controller/MomentControllerTest.java
- #292 
-> `memoryId`, `memoryTitle` 추가
> fix: 순간 조회 응답 필드 추가

- .github/workflows/android-ci-apk.yml
- .github/workflows/android-ci.yml
- #296
- 잘 돌아가는지 확인하고 마저 개발하기
- 난독화, 시멘틱 버저닝, 배포, CD 적용하기
> build: 구글 맵 API 사용에 따른 CI 수정 #296

- backend/src/main/resources/application-prod.yml
> chore: 운영 서버에서 명세서 비활성화 #302

- .github/workflows/android-cd.yml
- .github/workflows/android-ci-cd-demo-apk.yml
- .github/workflows/android-ci.yml
- android/Staccato_AN/app/build.gradle.kts
> build: Android CD 적용 #300

- .github/workflows/android-cd.yml
- .github/workflows/android-ci-cd-demo-apk.yml
- #317 
- upload-artifact 경로 2차 수정
> fix: android cd 재수정 (2차) #317

- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/dto/moment/MomentCreationRequest.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/data/moment/MomentDefaultRepository.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/domain/repository/MomentRepository.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/BindingAdapters.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/main/MainActivity.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/momentcreation/MomentCreationActivity.kt
- android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/momentcreation/viewmodel/MomentCreationViewModel.kt
- android/Staccato_AN/app/src/main/res/layout/activity_visit_creation.xml
- android/Staccato_AN/app/src/main/res/values/strings.xml
- #314
- 스타카토 생성 시 현 위치의 주소를 가져오는 기능
(추후 작성)
> feat: 스타카토 생성 시 현 위치의 주소를 가져오는 기능 구현 #314

- backend/src/main/java/com/staccato/memory/repository/MemoryMemberRepository.java
- backend/src/main/java/com/staccato/memory/repository/MemoryRepository.java
- backend/src/main/java/com/staccato/memory/service/MemoryService.java
- backend/src/test/java/com/staccato/memory/service/MemoryServiceTest.java
> fix: 사용자 추억 제목 중복 검증 버그 수정

- .github/workflows/android-cd.yml
- .github/workflows/android-ci-cd-demo-apk.yml.disabled
- .github/workflows/android-ci.yml
- .github/workflows/backend-ci-cd-dev.yml
- .github/workflows/backend-ci-cd-prod.yml
- .github/workflows/backend-ci-cd-stage.yml
- .github/workflows/backend-ci.yml
- #367
- `paths`옵션으로 android/backend 관련 수정 사항 발생했을 때만 관련 workflow 동작하도록 변경
- android workflow 트리거 변경
- 버전 관리 전략 회의
> chore: android/backed path & trigger 수정 #367

- .github/workflows/backend-ci-cd-stage.yml
- backend/build.gradle
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-prod.yml
- backend/src/main/resources/application-stage.yml
- backend/src/main/resources/db/migration/V1__init.sql
- backend/src/main/resources/db/migration/V2__alter_visited_at_to_datetime.sql
- backend/src/main/resources/db/migration/V3__alter_start_at_end_at_nullable.sql
- backend/src/main/resources/db/migration/V4__add_member_code.sql
- #381 
- stage서버에서 사용하는 DB를 별도의 EC2 인스턴스로 분리
- flyway 적용
> chore: stage서버에서 사용하는 DB를 별도의 EC2 인스턴스로 분리 및 flyway 적용 #381

- backend/src/main/java/com/staccato/moment/controller/MomentController.java
- backend/src/main/java/com/staccato/moment/controller/docs/MomentControllerDocs.java
- backend/src/main/java/com/staccato/moment/service/MomentService.java
- backend/src/main/java/com/staccato/moment/service/dto/response/MomentDetailResponseOldV.java
- #394 
- 기존 스타카토 조회 API 복구
빙티의 코드가 머지되어 기존 API가 필요 없어지는 시점이 되면, 삭제예정입니다!
> feat: 안드 개발상 편의를 위해 기존 스타카토 조회 API 복구 #394

- backend/src/main/java/com/staccato/image/service/ImageService.java
- backend/src/main/java/com/staccato/member/controller/MyPageController.java
- backend/src/main/java/com/staccato/member/controller/docs/MemberControllerDocs.java
- backend/src/main/java/com/staccato/member/controller/docs/MyPageControllerDocs.java
- backend/src/main/java/com/staccato/member/domain/Member.java
- backend/src/main/java/com/staccato/member/service/MemberService.java
- backend/src/main/java/com/staccato/member/service/dto/response/MemberProfileImageResponse.java
- backend/src/main/java/com/staccato/member/service/dto/response/MemberProfileResponse.java
- backend/src/test/java/com/staccato/member/controller/MyPageControllerTest.java
- backend/src/test/java/com/staccato/member/service/MemberServiceTest.java
> feat: 사용자 정보 조회 API #398

- backend/src/main/resources/application-dev.yml
- #429
- application-stage.yml -> application-dev.yml
> fix: 설정 파일 오류 수정 #429

- .github/workflows/backend-ci-cd-prod.yml
> chore: 운영 서버 docker 포트 포워딩 변경 #437

- android/Staccato_AN/app/build.gradle.kts
- #442
- versionCode: 3 -> 4
- versionName: "1.0.0" -> "1.1.0"
> build: 앱 버전 업데이트 #442

- android/Staccato_AN/app/src/main/res/values/strings.xml
- #463 
- 마이페이지에 나타나는 앱 버전 1.1.0으로 수정
> refactor: 마이페이지의 앱 버전 수정 #463

- .github/workflows/android-cd.yml
- .github/workflows/android-ci-cd-demo-apk.yml
- .github/workflows/android-ci.yml
> build: 누락된 android ci/cd 파일 복구 #465

- backend/src/main/resources/application-prod.yml
- flyway를 사용하기 위해서는 defer datasource initialization 설정을 비활성화해야합니다.
> hotfix: flyway 오류 수정

- backend/src/main/java/com/staccato/config/log/LoggingFilter.java
- #489 
- 헬스 체크, 모니터링 관련 요청을 whitelist로 추가했습니다.
> refactor: 로깅 whitelist 추가 #489

- android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memoryupdate/MemoryUpdateActivity.kt
- backend/src/main/java/com/staccato/config/log/LoggingFilter.java
- #484
- 무중단 배포 적용
- 로깅 whitelist 추가
> deploy: 1.1.1 배포 #484

- backend/src/main/resources/db/migration/V8__create_indexes.sql
> refactor: 인덱스 설정 #474

- backend/src/main/java/com/staccato/moment/domain/MomentImages.java
- #
- 이전 pr merge에서 release-be에 cascadeType 변경 사항이 반영되지 않아서 이와 같이 처리합니다.
- 스타카토 수정 시 삭제 전파 구현
> fix: file changed 인식 불가로 인한 순서 변경

- .github/workflows/android-ci.yml
> fix: 안드로이드 CI 오류 수정 #519

- .github/workflows/android-cd.yml
- #527 
- 데모용 APK 를 추출하는 CI/CD 의 필요 여부와 트리거 조건을 논의해보아야 할 것 같습니다.
- release-an 브랜치 추가하였습니다!
- 기도하기!
> fix: Android CD 수정 #527

- .github/workflows/backend-ci-cd-prod.yml
- backend/src/main/java/com/staccato/config/db/DataSourceConfig.java
- backend/src/main/java/com/staccato/config/db/DynamicRoutingDataSource.java
- backend/src/main/java/com/staccato/config/db/ReaderDataSourceConfig.java
- backend/src/main/java/com/staccato/config/db/WriterDataSourceConfig.java
- backend/src/main/resources/application-prod.yml
> chore: 운영환경 마이그레이션 #551

- android/Staccato_AN/app/src/main/java/com/on/staccato/data/comment/CommentApiService.kt
- #584 
- 서버의 변경에 따라, Comment API URI의 버저닝(`"v2"`)을 제거하였습니다.
- 늦어서 죄송합니다! 🥲
- Memory ➡️ Category 도메인명 변경하기
- 로그인 기능 UI 개선하기
> refactor: Comment Api의 버저닝 제거(v2 제거)

- .github/workflows/backend-ci-cd-multi-prod.yml
- #599 
개발 서버 배포 트리거를 `pull_request` 에서 `push`로 변경했습니다.
> refactor: 개발 서버 워크플로우 수정 (배포 트리거가 PR로 잘못 설정됨) #599

- backend/src/main/java/com/staccato/comment/controller/CommentController.java
- backend/src/main/java/com/staccato/comment/controller/docs/CommentControllerDocs.java
- backend/src/test/java/com/staccato/comment/controller/CommentControllerTest.java
> refactor: comment API 버저닝 제거 #584

- backend/src/test/java/com/staccato/comment/controller/CommentControllerTest.java
- #621 
- 실패하는 테스트 수정
- release-be branch를 develop branch에 머지 (Merge Conflict 해결)
> deploy: v.1.3.0 배포 준비 #621

- .github/workflows/android-cd.yml
- .github/workflows/android-ci-cd-dev.yml
- #624 
- 구현한 내용 설명1
- 구현한 내용 설명2
> build: Android CI&CD 수정 #624

- backend/src/main/java/com/staccato/category/service/CategoryFilter.java
- backend/src/main/java/com/staccato/category/service/CategorySort.java
- backend/src/main/java/com/staccato/category/service/dto/request/CategoryReadRequest.java
- backend/src/test/java/com/staccato/category/service/CategoryFilterTest.java
- backend/src/test/java/com/staccato/category/service/CategorySortTest.java
- backend/src/test/java/com/staccato/category/service/dto/request/CategoryReadRequestTest.java
- backend/src/test/java/com/staccato/config/log/ReadAllCategoryMetricsAspectTest.java
- backend/src/test/java/com/staccato/fixture/category/CategoryFixture.java
- #678
- 시간 상 일단 변경된 비즈니스 정책 반영 자체에 집중했습니다.
- 추후에 최적화와 리팩터링 방안에 대해 함께 논의 후 추가 작업 예정입니다.
- 변경된 정책은 이슈를 확인해주세요.
> feat: 정렬/필터링 API에 비즈니스 정책 변경 반영 #678

- .github/workflows/android-cd.yml
- .github/workflows/backend-ci-cd-prod.yml
- #659 
- 구현한 내용 설명1
- 구현한 내용 설명2
> chore: an/be CD 워크플로우 조건문 추가 #659

- backend/src/main/java/com/staccato/auth/service/dto/request/LoginRequest.java
- backend/src/main/java/com/staccato/auth/service/dto/response/LoginResponse.java
- backend/src/main/java/com/staccato/category/service/dto/request/CategoryReadRequest.java
- backend/src/main/java/com/staccato/category/service/dto/request/CategoryRequest.java
- backend/src/main/java/com/staccato/category/service/dto/response/CategoryDetailResponse.java
- backend/src/main/java/com/staccato/category/service/dto/response/CategoryIdResponse.java
- backend/src/main/java/com/staccato/category/service/dto/response/CategoryNameResponse.java
- backend/src/main/java/com/staccato/category/service/dto/response/CategoryResponse.java
- backend/src/main/java/com/staccato/category/service/dto/response/StaccatoResponse.java
- backend/src/main/java/com/staccato/comment/service/dto/request/CommentRequest.java
- backend/src/main/java/com/staccato/comment/service/dto/request/CommentUpdateRequest.java
- backend/src/main/java/com/staccato/comment/service/dto/response/CommentResponse.java
- backend/src/main/java/com/staccato/config/OpenApiConfig.java
- backend/src/main/java/com/staccato/config/swagger/SwaggerExamples.java
- backend/src/main/java/com/staccato/image/service/dto/ImageUrlResponse.java
- backend/src/main/java/com/staccato/member/service/dto/response/MemberProfileImageResponse.java
- backend/src/main/java/com/staccato/member/service/dto/response/MemberProfileResponse.java
- backend/src/main/java/com/staccato/member/service/dto/response/MemberResponse.java
- backend/src/main/java/com/staccato/staccato/service/dto/request/FeelingRequest.java
- backend/src/main/java/com/staccato/staccato/service/dto/request/StaccatoRequest.java
- backend/src/main/java/com/staccato/staccato/service/dto/response/CommentShareResponse.java
- backend/src/main/java/com/staccato/staccato/service/dto/response/StaccatoDetailResponse.java
- backend/src/main/java/com/staccato/staccato/service/dto/response/StaccatoIdResponse.java
- backend/src/main/java/com/staccato/staccato/service/dto/response/StaccatoLocationResponse.java
- backend/src/main/java/com/staccato/staccato/service/dto/response/StaccatoShareLinkResponse.java
- backend/src/main/java/com/staccato/staccato/service/dto/response/StaccatoSharedResponse.java
- closes #723
- [701 branch](https://github.com/woowacourse-teams/2024-staccato/pull/712)의 변경사항이 너무 컸다보니, 이 브랜치 머지 이전에 분기한 브랜치를 develop에 머지할때, merge conflict 해결이 굉장히 어렵습니다.
- 따라서, [714 branch](https://github.com/woowacourse-teams/2024-staccato/pull/719)를 develop에 머지하기 위해, 머지를 위한 브랜치를 파서 여기에 714 branch를 머지했습니다.
- 혹시나 701 branch 머지 전에 분기한 브랜치가 있으시면, 아예 새로운 브랜치를 파서 수동으로 작업 내용을 옮기거나, 저처럼 merge를 위한 브랜치를 파서 머지하는 것을 추천드립니다.
> fix: 714 branch merge conflict 해결하기 #723

- backend/build.gradle
> fix: spring boot trace 생성 관련 의존성 변경 #769

- backend/build.gradle
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-prod.yml
- backend/src/test/java/com/staccato/config/JasyptConfigTest.java
> fix: Tempo url 암호화 수정 #771

- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-prod.yml
> fix: Tempo url 암호화 최종 수정 #771

- backend/src/main/resources/application-dev.yml
> fix: 개발 서버 인증키 변경 #784

- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-prod.yml
- ci/cd 오류 발생으로, 재가동하기 위한 PR입니다.
> fix: ci/cd 재가동

- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-prod.yml
- #784 
- ci/cd 정상 작동을 위해 otel 설정을 롤백합니다.
> fix: 암호화 키 중복 문제 #784

- android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/bindingadapter/TextBindingAdapter.kt
- android/Staccato_AN/app/src/main/java/com/on/staccato/theme/Colors.kt
- android/Staccato_AN/app/src/main/res/values/colors.xml
- android/Staccato_AN/app/src/main/res/values/styles_text_input.xml
- #804 
- colors.xml 값 수정
- compose용 colors 추가
작성된 색상 값 중에 잘못된 부분이 없는지 확인 부탁드립니다~
> ui: 디자인 시스템 변경에 따른 컬러 값 수정 및 compose용 컬러 추가 #804

- android/Staccato_AN/app/src/main/java/com/on/staccato/theme/Typography.kt
- #812
<br>
- FontWeight와 Pretendard의 weight 값을 매핑하는 부분을 누락해 추가했습니다!
<br>
<br>
<br>
> ui: Font에 해당하는 weight 설정 #812

- backend/src/main/java/com/staccato/member/controller/MemberController.java
- backend/src/main/java/com/staccato/member/controller/MyPageControllerV2.java
- backend/src/main/java/com/staccato/member/controller/docs/MemberControllerDocs.java
- backend/src/main/java/com/staccato/member/controller/docs/MyPageControllerV2Docs.java
- backend/src/main/java/com/staccato/member/service/dto/response/MemberProfileResponseV2.java
- backend/src/test/java/com/staccato/member/controller/MyPageControllerV2Test.java
> feat: 사용자 식별자 응답 필드를 추가한 mypage V2 API 구현

- backend/src/main/java/com/staccato/category/domain/Category.java
- backend/src/main/java/com/staccato/category/service/CategoryService.java
- backend/src/test/java/com/staccato/category/domain/CategoryTest.java
- https://github.com/woowacourse-teams/2024-staccato/pull/907#issue-3143502677
- 이 브랜치에서 push 빠뜨린 commit 다시 추가해서 머지합니다.
> fix: commit push 빠뜨림

- .github/workflows/develop-up-to-date-checker.yml
- #908
- 이슈를 확인해주세요!
- workflow 내 명령어 정상 동작을 확인했습니다!
- 불필요한 workflow일 것 같다면 pr close 예정입니다~
> chore: 최신 develop 브랜치 반영 여부 확인하는 workflow 작성 #908
